Delete a Role
---
tags:
  - Roles
parameters:
  - in: header
    name: Authorization
    type: string
  - in: path
    name: row_id
    schema:
      type: int
    required: true
    description: 'The role to delete'
responses:
  204:
    description: 'role deleted'
  404:
    description: 'Role id: <row_id> does not exist'
  500:
    description: 'Some unknown exception!'