COMPANY_PROFILE_SNAPSHOT = 'COMPANY_PROFILE_SNAPSHOT'
OWNERSHIP_ANALYSIS_SNAPSHOT = 'OWNERSHIP_ANALYSIS_SNAPSHOT'
DETAILED_OWNERSHIP_ANALYSIS = 'DETAILED_OWNERSHIP_ANALYSIS'
INVESTOR_PROFILE = 'INVESTOR_PROFILE'
DISCLOSURES_ENHANCEMENT = 'DISCLOSURES_ENHANCEMENT'
OWNERSHIP_INVESTOR_PROFILE = 'OWNERSHIP_PROFILE_INSTITUTION'
OWNERSHIP_INVESTOR_PROFILE_FUND = 'OWNERSHIP_PROFILE_FUND'
INVESTOR_TARGETING_SCREENING = 'INVESTOR_TARGETING_SCREENING'

SCH_REPORT_TYPES = [ COMPANY_PROFILE_SNAPSHOT, OWNERSHIP_ANALYSIS_SNAPSHOT,
    DETAILED_OWNERSHIP_ANALYSIS, INVESTOR_PROFILE, DISCLOSURES_ENHANCEMENT,
    OWNERSHIP_INVESTOR_PROFILE, OWNERSHIP_INVESTOR_PROFILE_FUND,
    INVESTOR_TARGETING_SCREENING]

SCH_REPORT_TYPE_CHOICES = [(c, c) for c in SCH_REPORT_TYPES]

SCH_REPORT_URLS = {
    COMPANY_PROFILE_SNAPSHOT: 'company-profile-snapshot',
    OWNERSHIP_ANALYSIS_SNAPSHOT: 'ownership-analysis-snapshot',
    DETAILED_OWNERSHIP_ANALYSIS: 'ownership-analysis-detail',
    INVESTOR_PROFILE: 'ownership-investor-profile',
    DISCLOSURES_ENHANCEMENT: 'disclosures-enhancement',
    OWNERSHIP_INVESTOR_PROFILE: 'ownership-investor-profile',
    OWNERSHIP_INVESTOR_PROFILE_FUND: 'ownership-investor-profile-fund',
    INVESTOR_TARGETING_SCREENING: 'investor-targeting-screening'}

DAILY = 'Daily'
WEEKLY = 'Weekly'
MONTHLY = 'Monthly'
YEARLY = 'Yearly'
FREQUENCY_TYPES = [DAILY, WEEKLY, MONTHLY, YEARLY]
FREQUENCT_TYPE_CHOICES = [(f, f) for f in FREQUENCY_TYPES]

SENT = 'sent'
UNSENT = 'unsent'
SCH_REPORT_STATUS_TYPES = [SENT, UNSENT]
SCH_REPORT_STATUS_CHOICES = [(x, x) for x in SCH_REPORT_STATUS_TYPES]


TIMEDELTA_PARAMS = {
    DAILY: 'days',
    WEEKLY: 'weeks',
    MONTHLY: 'months',
    YEARLY: 'years'
}

# time in minutes
CRON_TIME_INTERVAL = 30
