"""empty message

Revision ID: 01b160dc767d
Revises: 8555dba5a3c7
Create Date: 2018-07-25 15:51:16.116352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01b160dc767d'
down_revision = 'bfc64779f03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('comment', 'help_comment')
    op.execute('ALTER SEQUENCE comment_id_seq RENAME TO help_comment_id_seq')
    op.execute('ALTER INDEX comment_pkey RENAME TO help_comment_pkey')
    op.drop_constraint('comment_created_by_fkey', 'help_comment', type_='foreignkey')
    op.drop_constraint('comment_ticket_id_fkey', 'help_comment', type_='foreignkey')

    op.rename_table('ticket', 'help_ticket')
    op.execute('ALTER SEQUENCE ticket_id_seq RENAME TO help_ticket_id_seq')
    op.execute('ALTER INDEX ticket_pkey RENAME TO help_ticket_pkey')
    op.drop_constraint('ticket_created_by_fkey', 'help_ticket', type_='foreignkey')
    op.drop_constraint('ticket_assignee_id_fkey', 'help_ticket', type_='foreignkey')

    op.create_foreign_key('help_comment_created_by_fkey', 'help_comment', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('help_comment_ticket_id_fkey', 'help_comment', 'help_ticket', ['ticket_id'], ['id'], ondelete='CASCADE')

    op.create_foreign_key('help_ticket_created_by_fkey', 'help_ticket', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('help_ticket_assignee_id_fkey', 'help_ticket', 'user', ['assignee_id'], ['id'], ondelete='SET NULL')

    op.add_column('help_comment', sa.Column('updated_by', sa.BigInteger()))
    op.create_foreign_key('help_comment_updated_by_fkey', 'help_comment', 'user', ['updated_by'], ['id'], ondelete='CASCADE')
    op.add_column('help_ticket', sa.Column('updated_by', sa.BigInteger()))
    op.create_foreign_key('help_ticket_updated_by_fkey', 'help_ticket', 'user', ['updated_by'], ['id'], ondelete='CASCADE')
    op.execute("UPDATE help_comment SET updated_by=created_by")
    op.execute("UPDATE help_ticket SET updated_by=created_by")
    op.alter_column('help_comment', 'updated_by', nullable=False)
    op.alter_column('help_ticket', 'updated_by', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('help_ticket_updated_by_fkey', 'help_ticket', type_='foreignkey')
    op.drop_column('help_ticket', 'updated_by')
    op.drop_constraint('help_comment_updated_by_fkey', 'help_comment', type_='foreignkey')
    op.drop_column('help_comment', 'updated_by')

    op.rename_table('help_comment', 'comment')
    op.execute('ALTER SEQUENCE help_comment_id_seq RENAME TO comment_id_seq')
    op.execute('ALTER INDEX help_comment_pkey RENAME TO comment_pkey')
    op.drop_constraint('help_comment_created_by_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('help_comment_ticket_id_fkey', 'comment', type_='foreignkey')

    op.rename_table('help_ticket', 'ticket')
    op.execute('ALTER SEQUENCE help_ticket_id_seq RENAME TO ticket_id_seq')
    op.execute('ALTER INDEX help_ticket_pkey RENAME TO ticket_pkey')
    op.drop_constraint('help_ticket_created_by_fkey', 'ticket', type_='foreignkey')
    op.drop_constraint('help_ticket_assignee_id_fkey', 'ticket', type_='foreignkey')

    op.create_foreign_key('comment_created_by_fkey', 'comment', 'user', ['created_by'], ['id'])
    op.create_foreign_key('comment_ticket_id_fkey', 'comment', 'ticket', ['ticket_id'], ['id'])

    op.create_foreign_key('ticket_created_by_fkey', 'ticket', 'user', ['created_by'], ['id'])
    op.create_foreign_key('ticket_assignee_id_fkey', 'ticket', 'user', ['assignee_id'], ['id'])
    # ### end Alembic commands ###
