"""empty message

Revision ID: 0207bc5e3a50
Revises: 267e9cc49b29
Create Date: 2020-06-06 11:10:44.040986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0207bc5e3a50'
down_revision = '267e9cc49b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE market_analyst_comment ALTER COLUMN comment TYPE varchar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE market_analyst_comment ALTER COLUMN comment TYPE varchar(4096)')
    # ### end Alembic commands ###
