"""empty message

Revision ID: 080193de7517
Revises: 28926377d629
Create Date: 2021-01-11 10:32:20.092439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '080193de7517'
down_revision = '3dcb19d384df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.add_column('cron_job', sa.Column('domain_id', sa.BigInteger(), nullable=True))
    op.add_column('cron_job', sa.Column('time', sa.Time(), nullable=True))
    op.add_column('cron_job', sa.Column('timezone', sa.String(), nullable=True))
    op.create_foreign_key('cron_job_domain_id_fkey', 'cron_job', 'domain', ['domain_id'], ['id'])"""
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cron_job_domain_id_fkey', 'cron_job', type_='foreignkey')
    op.drop_column('cron_job', 'timezone')
    op.drop_column('cron_job', 'time')
    op.drop_column('cron_job', 'domain_id')
    # ### end Alembic commands ###