"""empty message

Revision ID: 0c151dbf2c8c
Revises: 6997213417e6
Create Date: 2018-04-18 18:09:49.079263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c151dbf2c8c'
down_revision = '6997213417e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_attendee', sa.Column('invitee_id', sa.BigInteger(), nullable=True))
    op.alter_column('corporate_access_event_attendee', 'attendee_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint('c_cracs_event_id_attendee_id_key', 'corporate_access_event_attendee', ['corporate_access_event_id', 'attendee_id'])
    op.create_unique_constraint('c_cracs_event_id_invitee_id_key', 'corporate_access_event_attendee', ['corporate_access_event_id', 'invitee_id'])
    op.create_foreign_key('corporate_access_event_attendee_invitee_id_fkey', 'corporate_access_event_attendee', 'corporate_access_event_invitee', ['invitee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('corporate_access_event_attendee_invitee_id_fkey', 'corporate_access_event_attendee', type_='foreignkey')
    op.drop_constraint('c_cracs_event_id_invitee_id_key', 'corporate_access_event_attendee', type_='unique')
    op.drop_constraint('c_cracs_event_id_attendee_id_key', 'corporate_access_event_attendee', type_='unique')
    op.alter_column('corporate_access_event_attendee', 'attendee_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('corporate_access_event_attendee', 'invitee_id')
    # ### end Alembic commands ###
