"""empty message

Revision ID: 0c3862dbd686
Revises: e3fb7fbc3339
Create Date: 2018-08-14 17:03:51.115003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3862dbd686'
down_revision = 'e3fb7fbc3339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'industry_name')
    op.drop_column('company', 'sector_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('sector_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('industry_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
