"""empty message

Revision ID: 0ca22e8b818b
Revises: e9294c2c0b3b
Create Date: 2019-05-10 13:31:38.094336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ca22e8b818b'
down_revision = '9736902c606d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('keywords', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'keywords')

    # ### end Alembic commands ###
