"""empty message

Revision ID: 0fa096bc5de8
Revises: ad2de29b2eb6
Create Date: 2019-05-21 19:14:46.200861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fa096bc5de8'
down_revision = '8da09cefe305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event', sa.Column('country', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event', sa.Column('state', sa.String(length=128), nullable=True))
    op.add_column('ca_open_meeting',
                  sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('ca_open_meeting',
                  sa.Column('country', sa.String(length=128), nullable=True))
    op.add_column('ca_open_meeting',
                  sa.Column('state', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event', 'state')
    op.drop_column('corporate_access_event', 'country')
    op.drop_column('corporate_access_event', 'city')
    op.drop_column('ca_open_meeting', 'state')
    op.drop_column('ca_open_meeting', 'country')
    op.drop_column('ca_open_meeting', 'city')
    # ### end Alembic commands ###
