"""empty message

Revision ID: 10a13940e931
Revises: 5f85be3e9fa8
Create Date: 2018-04-13 18:10:22.614816

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '10a13940e931'
down_revision = '5f85be3e9fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_invitee', sa.Column('status', app.base.model_fields.ChoiceString(app.corporate_access_resources.corporate_access_event_invitees.constants.EVT_INV_STATUS_CHOICES)))
    op.execute("UPDATE corporate_access_event_invitee SET status='" + app.corporate_access_resources.corporate_access_event_invitees.constants.INVITED + "'")
    op.alter_column('corporate_access_event_invitee', 'status', nullable=False)

    op.add_column('corporate_access_event_stats', sa.Column('total_joined', sa.BigInteger(), nullable=True))
    op.execute("UPDATE corporate_access_event_stats SET total_joined=0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event_stats', 'total_joined')
    op.drop_column('corporate_access_event_invitee', 'status')
    # ### end Alembic commands ###
