"""empty message

Revision ID: 1623fb76bf51
Revises: 1b4ee61507c4
Create Date: 2018-04-05 17:54:05.396336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1623fb76bf51'
down_revision = '1b4ee61507c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_stats', sa.Column('total_files', sa.BigInteger(), nullable=True))
    op.add_column('webcast_stats', sa.Column('total_files', sa.BigInteger(), nullable=True))
    op.add_column('webinar_stats', sa.Column('total_files', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_stats', 'total_files')
    op.drop_column('webcast_stats', 'total_files')
    op.drop_column('corporate_access_event_stats', 'total_files')
    # ### end Alembic commands ###
