"""empty message

Revision ID: 17abd73e8f56
Revises: c30ac9fc6dff
Create Date: 2021-12-27 14:51:10.724300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision = '17abd73e8f56'
down_revision = 'c30ac9fc6dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bse_mf_etf_feed',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('scrip_cd', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('dt_tm', sa.DateTime(), nullable=True),
    sa.Column('file_status', sa.String(), nullable=True),
    sa.Column('head_line', sa.String(), nullable=True),
    sa.Column('news_sub', sa.String(), nullable=True),
    sa.Column('attachment_name', sa.String(), nullable=True),
    sa.Column('news_body', sa.String(), nullable=True),
    sa.Column('descriptor', sa.String(), nullable=True),
    sa.Column('critical_news', sa.String(), nullable=True),
    sa.Column('type_of_announce', sa.String(), nullable=True),
    sa.Column('type_of_meeting', sa.String(), nullable=True),
    sa.Column('date_of_meeting', sa.DateTime(), nullable=True),
    sa.Column('descriptor_id', sa.BigInteger(), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('trade_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bse_corp_feed', sa.Column('is_mfetf', sa.Boolean(), nullable=True))
    op.add_column('bse_corp_feed', sa.Column('trade_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bse_corp_feed', 'trade_date')
    op.drop_column('bse_corp_feed', 'is_mfetf')
    op.drop_table('bse_mf_etf_feed')
    # ### end Alembic commands ###
