"""empty message

Revision ID: 184a77948ed0
Revises: 263895e259dc
Create Date: 2018-04-30 15:18:15.916368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184a77948ed0'
down_revision = '263895e259dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_invitee', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('corporate_access_event_invitee_user_id_fkey', 'corporate_access_event_invitee', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('corporate_access_event_invitee_user_id_fkey', 'corporate_access_event_invitee', type_='foreignkey')
    op.drop_column('corporate_access_event_invitee', 'user_id')
    # ### end Alembic commands ###
