"""empty message

Revision ID: 1a87414aae2e
Revises: b10f33e43edf
Create Date: 2021-11-23 20:23:55.850107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a87414aae2e'
down_revision = '82d8e2c51fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_transcribe', sa.Column('email_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_transcribe', 'email_status')
    # ### end Alembic commands ###
