"""empty message

Revision ID: 1be4ea4aba54
Revises: ebf85bef23c9
Create Date: 2021-11-24 17:29:38.369323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1be4ea4aba54'
down_revision = '9afa366f669d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_transcribe', sa.Column('acc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audio_transcribe', 'account', ['acc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio_transcribe', type_='foreignkey')
    op.drop_column('audio_transcribe', 'acc_id')
    # ### end Alembic commands ###
