"""empty message

Revision ID: 1c8d6c06f588
Revises: 204f5a9dd1c2
Create Date: 2019-04-12 11:38:51.527472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c8d6c06f588'
down_revision = '204f5a9dd1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_host', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webinar_host set is_mail_sent='t'")
    op.add_column('webinar_invitee', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webinar_invitee set is_mail_sent='t'")
    op.add_column('webinar_participant', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webinar_participant set is_mail_sent='t'")
    op.add_column('webinar_rsvp', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webinar_rsvp set is_mail_sent='t'")
    op.add_column('survey_response',
                  sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update survey_response set is_mail_sent='t'")
    op.add_column('webcast_host',
                  sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webcast_host set is_mail_sent='t'")
    op.add_column('webcast_invitee',
                  sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webcast_invitee set is_mail_sent='t'")
    op.add_column('webcast_participant',
                  sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webcast_participant set is_mail_sent='t'")
    op.add_column('webcast_rsvp',
                  sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webcast_rsvp set is_mail_sent='t'")
    op.add_column('corporate_access_event',
                  sa.Column('is_in_process', sa.Boolean(),
                            nullable=True))
    op.execute("update corporate_access_event set is_in_process='f'")
    op.add_column('survey',
                  sa.Column('is_in_process', sa.Boolean(), nullable=True))
    op.execute("update survey set is_in_process='f'")
    op.add_column('webcast',
                  sa.Column('is_in_process', sa.Boolean(), nullable=True))
    op.execute("update webcast set is_in_process='f'")
    op.add_column('webinar',
                  sa.Column('is_in_process', sa.Boolean(), nullable=True))
    op.execute("update webinar set is_in_process='f'")
    op.add_column('corporate_access_event',
                  sa.Column('creator_mail_sent', sa.Boolean(), nullable=True))
    op.execute(
        "update corporate_access_event set creator_mail_sent='t' where is_draft = 'f'")
    op.execute(
        "update corporate_access_event set creator_mail_sent='f' where is_draft = 't'")
    op.add_column('survey',
                  sa.Column('creator_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update survey set creator_mail_sent='f' where editable='t'")
    op.execute("update survey set creator_mail_sent='t' where editable='f'")
    op.add_column('webcast',
                  sa.Column('creator_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webcast set creator_mail_sent='t' where is_draft = 'f'")
    op.execute("update webcast set creator_mail_sent='f' where is_draft = 't'")
    op.add_column('webinar',
                  sa.Column('creator_mail_sent', sa.Boolean(), nullable=True))
    op.execute("update webinar set creator_mail_sent='t' where is_draft = 'f'")
    op.execute("update webinar set creator_mail_sent='f' where is_draft = 't'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_rsvp', 'is_mail_sent')
    op.drop_column('webinar_participant', 'is_mail_sent')
    op.drop_column('webinar_invitee', 'is_mail_sent')
    op.drop_column('webinar_host', 'is_mail_sent')
    op.drop_column('webcast_rsvp', 'is_mail_sent')
    op.drop_column('webcast_participant', 'is_mail_sent')
    op.drop_column('webcast_invitee', 'is_mail_sent')
    op.drop_column('webcast_host', 'is_mail_sent')
    op.drop_column('survey_response', 'is_mail_sent')
    op.drop_column('corporate_access_event', 'is_in_process')
    op.drop_column('webinar', 'is_in_process')
    op.drop_column('webcast', 'is_in_process')
    op.drop_column('survey', 'is_in_process')
    op.drop_column('webinar', 'creator_mail_sent')
    op.drop_column('webcast', 'creator_mail_sent')
    op.drop_column('survey', 'creator_mail_sent')
    op.drop_column('corporate_access_event', 'creator_mail_sent')
    # ### end Alembic commands ###
