"""empty message

Revision ID: 1d9b4ec155f7
Revises: cbd26a0de3b3
Create Date: 2018-03-23 16:06:05.444079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d9b4ec155f7'
down_revision = 'cbd26a0de3b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar', sa.Column('open_to_account_types', postgresql.ARRAY(sa.String(length=256)), nullable=True))
    op.add_column('webinar', sa.Column('open_to_all', sa.Boolean(), nullable=True))
    op.execute("UPDATE webinar SET open_to_all=true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar', 'open_to_all')
    op.drop_column('webinar', 'open_to_account_types')
    # ### end Alembic commands ###
