"""empty message

Revision ID: 1e91172e3671
Revises: bc075dc6fe44
Create Date: 2019-10-03 05:53:45.510592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e91172e3671'
down_revision = 'bc075dc6fe44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_report_parameter', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('research_report',
                  sa.Column('xml_file', sa.String(), nullable=True))
    parameter_names = ['Introduction', 'Industry', 'Financials', 'Dividend',
                       'People', 'Outlook', 'Key Segment', 'International Business',
                       'Strengths', 'Weaknesses', 'Opportunities', 'Threats',
                       'Risk Management', 'Summary']
    for i in range(14):
        op.execute("update research_report_parameter  set sequence = {} where "
                   "parameter_name = '{}';".format(i+1, parameter_names[i]))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_report_parameter', 'sequence')
    op.drop_column('research_report', 'xml_file')
    # ### end Alembic commands ###
