"""empty message

Revision ID: 22eecd95626e
Revises: ac2a409a8d0c
Create Date: 2019-07-12 15:22:17.534268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22eecd95626e'
down_revision = '3af0364f0ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('report_download_limit', sa.Integer(),
                                    server_default='0', nullable=True))
    op.add_column('user', sa.Column('report_downloaded', sa.Integer(),
                                    server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'report_downloaded')
    op.drop_column('user', 'report_download_limit')
    # ### end Alembic commands ###
