"""empty message

Revision ID: 2413449714e5
Revises: f66419b37cd8
Create Date: 2018-05-15 00:08:18.936428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2413449714e5'
down_revision = 'f66419b37cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('c_country_id_state_id_city_name_key', 'city', type_='unique')
    op.create_index('ci_country_id_state_id_city_name_key', 'city', ['country_id', 'state_id', sa.text('lower(city_name)')], unique=True)

    op.add_column('country', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.drop_constraint('country_country_name_key', 'country', type_='unique')
    op.create_index('ci_country_unique_name', 'country', [sa.text('lower(country_name)')], unique=True)
    op.create_index('ci_country_unique_code', 'country', [sa.text('lower(country_code)')], unique=True)

    op.add_column('state', sa.Column('state_code', sa.String(length=16), nullable=True))
    op.drop_constraint('c_country_id_state_name_key', 'state', type_='unique')
    op.create_index('ci_state_country_id_state_name_key', 'state', ['country_id', sa.text('lower(state_name)')], unique=True)
    op.create_index('ci_state_state_code_key', 'state', [sa.text('lower(state_code)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('c_country_id_state_name_key', 'state', ['country_id', 'state_name'])
    op.drop_column('state', 'state_code')
    op.drop_index('ci_state_country_id_state_name_key', 'state')
    op.drop_index('ci_state_state_code_key', 'state')

    op.create_unique_constraint('country_country_name_key', 'country', ['country_name'])
    op.drop_index('ci_country_unique_name', 'country')
    op.drop_index('ci_country_unique_code', 'country')
    op.drop_column('country', 'country_code')

    op.create_unique_constraint('c_country_id_state_id_city_name_key', 'city', ['country_id', 'state_id', 'city_name'])
    op.drop_index('ci_country_id_state_id_city_name_key', 'city')
    # ### end Alembic commands ###
