"""empty message

Revision ID: 263895e259dc
Revises: 97a5aa918537
Create Date: 2018-04-20 17:00:12.253826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app


# revision identifiers, used by Alembic.
revision = '263895e259dc'
down_revision = '97a5aa918537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_page', sa.Column('assets', app.base.model_fields.CastingArray(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_page', 'assets')
    # ### end Alembic commands ###
