"""empty message

Revision ID: 2644b9c196cb
Revises: 5f17e4627e1d
Create Date: 2018-03-30 19:00:22.666476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2644b9c196cb'
down_revision = '5f17e4627e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_profile', sa.Column('industry_id', sa.BigInteger(), nullable=True))
    # alter name
    op.alter_column('account_profile', 'industry', new_column_name='industry_name')
    op.add_column('account_profile', sa.Column('sector_id', sa.BigInteger(), nullable=True))
    # alter name
    op.alter_column('account_profile', 'sector', new_column_name='sector_name')
    op.create_foreign_key('account_profile_sector_id_fkey', 'account_profile', 'sector', ['sector_id'], ['id'])
    op.create_foreign_key('account_profile_industry_id_fkey', 'account_profile', 'industry', ['industry_id'], ['id'])
    op.add_column('user_profile', sa.Column('industry_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True))
    # alter name
    op.alter_column('user_profile', 'industries', new_column_name='industry_names')
    op.add_column('user_profile', sa.Column('sector_ids', postgresql.ARRAY(sa.BigInteger()), nullable=True))
    # alter name
    op.alter_column('user_profile', 'sectors', new_column_name='sector_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'sector_names', new_column_name='sectors')
    op.alter_column('user_profile', 'industry_names', new_column_name='industries')
    op.drop_column('user_profile', 'sector_ids')
    op.drop_column('user_profile', 'industry_ids')
    op.alter_column('account_profile', 'sector_name', new_column_name='sector')
    op.alter_column('account_profile', 'industry_name', new_column_name='industry')
    op.drop_constraint('account_profile_industry_id_fkey', 'account_profile', type_='foreignkey')
    op.drop_constraint('account_profile_sector_id_fkey', 'account_profile', type_='foreignkey')
    op.drop_column('account_profile', 'sector_id')
    op.drop_column('account_profile', 'industry_id')
    # ### end Alembic commands ###
