"""empty message

Revision ID: 270757dc93ae
Revises: b36e5fa8c0b4
Create Date: 2021-11-08 18:10:55.331197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '270757dc93ae'
down_revision = 'c3e04c6efa6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bse_corp_feed', sa.Column('source', sa.String(), nullable=True))
    op.add_column('corporate_announcement', sa.Column('concall_date', sa.DateTime(), nullable=True))
    op.drop_column('corporate_announcement', 'conall_date')
    # op.add_column('corporate_announcement', sa.Column('result_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_announcement', sa.Column('conall_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # op.drop_column('corporate_announcement', 'result_date')
    op.drop_column('corporate_announcement', 'concall_date')
    op.drop_column('bse_corp_feed', 'source')
    # ### end Alembic commands ###
