"""empty message

Revision ID: 2775da5ddcf4
Revises: a0e1ebaddd7e
Create Date: 2018-02-19 18:36:06.137148

"""
from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision = '2775da5ddcf4'
down_revision = 'a0e1ebaddd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('account_type', app.base.model_fields.ChoiceString(app.resources.accounts.constants.ACCT_TYPES_CHOICES)))
    op.execute("UPDATE company SET account_type='" + app.resources.accounts.constants.ACCT_CORPORATE + "'")
    op.alter_column('company', 'account_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'account_type')
    # ### end Alembic commands ###
