"""empty message

Revision ID: 29a343154f6c
Revises: 551bdfcfb445
Create Date: 2018-07-02 13:26:44.527802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a343154f6c'
down_revision = '551bdfcfb445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_parameter', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('ref_project_parameter', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_project_parameter', 'level')
    op.drop_column('project_parameter', 'level')
    # ### end Alembic commands ###
