"""empty message

Revision ID: 2be8d7abb34a
Revises: 96c2a2c79582
Create Date: 2018-03-22 18:14:30.828377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be8d7abb34a'
down_revision = '96c2a2c79582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast_participant', sa.Column('participant_designation', sa.String(length=128), nullable=True))
    op.create_unique_constraint('c_webcast_id_invitee_email_key', 'webcast_invitee', ['webcast_id', 'invitee_email'])
    op.create_unique_constraint('c_webcast_id_invitee_id_key', 'webcast_invitee', ['webcast_id', 'invitee_id'])
    op.drop_constraint('c_webcast_id_invitee_id_invitee_email_key', 'webcast_invitee', type_='unique')
    op.create_unique_constraint('c_webcast_id_participant_email_key', 'webcast_participant', ['webcast_id', 'participant_email'])
    op.create_unique_constraint('c_webcast_id_participant_id_key', 'webcast_participant', ['webcast_id', 'participant_id'])
    op.drop_constraint('c_webcast_id_participant_id_participant_email_key', 'webcast_participant', type_='unique')
    op.create_unique_constraint('c_webinar_id_host_email_key', 'webinar_host', ['webinar_id', 'host_email'])
    op.create_unique_constraint('c_webinar_id_invitee_email_key', 'webinar_invitee', ['webinar_id', 'invitee_email'])
    op.create_unique_constraint('c_webinar_id_invitee_id_key', 'webinar_invitee', ['webinar_id', 'invitee_id'])
    op.drop_constraint('c_webinar_id_invitee_id_invitee_email_key', 'webinar_invitee', type_='unique')
    op.create_unique_constraint('c_webinar_id_participant_email_key', 'webinar_participant', ['webinar_id', 'participant_email'])
    op.create_unique_constraint('c_webinar_id_participant_id_key', 'webinar_participant', ['webinar_id', 'participant_id'])
    op.drop_constraint('c_webinar_id_participant_id_participant_email_key', 'webinar_participant', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('c_webinar_id_participant_id_participant_email_key', 'webinar_participant', ['webinar_id', 'participant_id', 'participant_email'])
    op.drop_constraint('c_webinar_id_participant_id_key', 'webinar_participant', type_='unique')
    op.drop_constraint('c_webinar_id_participant_email_key', 'webinar_participant', type_='unique')
    op.create_unique_constraint('c_webinar_id_invitee_id_invitee_email_key', 'webinar_invitee', ['webinar_id', 'invitee_id', 'invitee_email'])
    op.drop_constraint('c_webinar_id_invitee_id_key', 'webinar_invitee', type_='unique')
    op.drop_constraint('c_webinar_id_invitee_email_key', 'webinar_invitee', type_='unique')
    op.drop_constraint('c_webinar_id_host_email_key', 'webinar_host', type_='unique')
    op.create_unique_constraint('c_webcast_id_participant_id_participant_email_key', 'webcast_participant', ['webcast_id', 'participant_id', 'participant_email'])
    op.drop_constraint('c_webcast_id_participant_id_key', 'webcast_participant', type_='unique')
    op.drop_constraint('c_webcast_id_participant_email_key', 'webcast_participant', type_='unique')
    op.create_unique_constraint('c_webcast_id_invitee_id_invitee_email_key', 'webcast_invitee', ['webcast_id', 'invitee_id', 'invitee_email'])
    op.drop_constraint('c_webcast_id_invitee_id_key', 'webcast_invitee', type_='unique')
    op.drop_constraint('c_webcast_id_invitee_email_key', 'webcast_invitee', type_='unique')
    op.drop_column('webcast_participant', 'participant_designation')
    # ### end Alembic commands ###
