"""empty message

Revision ID: 2ce3865f8250
Revises: afb862103eb1
Create Date: 2019-01-18 16:11:45.805030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ce3865f8250'
down_revision = '8d8850d34354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ca_open_meeting', 'alternative_dial_in_detail',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('ca_open_meeting', 'dial_in_detail',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('corporate_access_event', 'alternative_dial_in_detail',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('corporate_access_event', 'dial_in_detail',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('corporate_access_event', 'other_invitees',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('crm_contact', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_contact', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('corporate_access_event', 'other_invitees',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('corporate_access_event', 'dial_in_detail',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('corporate_access_event', 'alternative_dial_in_detail',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('ca_open_meeting', 'dial_in_detail',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('ca_open_meeting', 'alternative_dial_in_detail',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
