"""empty message

Revision ID: 302ac347ebd4
Revises: 3cac26245526
Create Date: 2018-10-23 18:15:25.262998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision = '302ac347ebd4'
down_revision = '89fb41b3a7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast', sa.Column('admin_url', sa.String(length=256), nullable=True))
    op.add_column('webcast', sa.Column('conference_id', sa.String(length=128), nullable=True))
    op.add_column('webcast_attendee', sa.Column('browser_name', sa.String(length=128), nullable=True))
    op.add_column('webcast_attendee', sa.Column('browser_version', sa.String(length=128), nullable=True))
    op.add_column('webcast_attendee', sa.Column('chats_count', sa.BigInteger(), nullable=True))
    op.add_column('webcast_attendee', sa.Column('device_name', sa.String(length=128), nullable=True))
    op.add_column('webcast_attendee', sa.Column('engaged_duration', sa.String(length=16), nullable=True))
    op.add_column('webcast_attendee', sa.Column('entered_at', sa.DateTime(), nullable=True))
    op.add_column('webcast_attendee', sa.Column('handouts', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('webcast_attendee', sa.Column('leaved_at', sa.DateTime(), nullable=True))
    op.add_column('webcast_attendee', sa.Column('polls', app.base.model_fields.CastingArray(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    op.add_column('webcast_attendee', sa.Column('polls_count', sa.BigInteger(), nullable=True))
    op.add_column('webcast_attendee', sa.Column('qas_count', sa.BigInteger(), nullable=True))
    op.add_column('webcast_attendee', sa.Column('questions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('webcast_attendee', sa.Column('total_duration', sa.String(length=16), nullable=True))
    op.add_column('webcast_host', sa.Column('conference_url', sa.String(length=256), nullable=True))
    op.add_column('webcast_participant', sa.Column('conference_url', sa.String(length=256), nullable=True))
    op.add_column('webcast_rsvp', sa.Column('conference_url', sa.String(length=256), nullable=True))
    op.add_column('webcast_invitee', sa.Column('conference_url', sa.String(length=256), nullable=True))
    op.add_column('webcast_invitee', sa.Column('status', app.base.model_fields.ChoiceString(app.webcast_resources.webcast_invitees.constants.WBCT_INV_STATUS_CHOICES)))
    op.execute("UPDATE webcast_invitee SET status='" + app.webcast_resources.webcast_invitees.constants.INVITED + "'")
    op.alter_column('webcast_invitee', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webcast_invitee', 'status')
    op.drop_column('webcast_invitee', 'conference_url')
    op.drop_column('webcast_rsvp', 'conference_url')
    op.drop_column('webcast_participant', 'conference_url')
    op.drop_column('webcast_host', 'conference_url')
    op.drop_column('webcast_attendee', 'total_duration')
    op.drop_column('webcast_attendee', 'questions')
    op.drop_column('webcast_attendee', 'qas_count')
    op.drop_column('webcast_attendee', 'polls_count')
    op.drop_column('webcast_attendee', 'polls')
    op.drop_column('webcast_attendee', 'leaved_at')
    op.drop_column('webcast_attendee', 'handouts')
    op.drop_column('webcast_attendee', 'entered_at')
    op.drop_column('webcast_attendee', 'engaged_duration')
    op.drop_column('webcast_attendee', 'device_name')
    op.drop_column('webcast_attendee', 'chats_count')
    op.drop_column('webcast_attendee', 'browser_version')
    op.drop_column('webcast_attendee', 'browser_name')
    op.drop_column('webcast', 'conference_id')
    op.drop_column('webcast', 'admin_url')
    # ### end Alembic commands ###
