"""empty message

Revision ID: 35d81f89a521
Revises: 1dfb40183db8
Create Date: 2021-09-24 16:55:57.297541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35d81f89a521'
# down_revision = 'eeebc233e920'
# down_revision = '1dfb40183db8'
down_revision = '0d4bca658d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_announcement', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'corporate_announcement', 'corporate_announcement_category', ['category_id'], ['id'])
    op.add_column('notification', sa.Column('bse_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('notification_bse_id_fkey', 'notification', 'bse_corp_feed', ['bse_id'], ['id'], ondelete='CASCADE')
    op.add_column('descriptor_master', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bse_corp_feed', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('bse_corp_feed', sa.Column('ec_category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bse_corp_feed', 'corporate_announcement_category', ['ec_category'], ['id'])
    op.create_foreign_key(None, 'bse_corp_feed', 'account', ['account_id'], ['id'])
    op.create_foreign_key(None, 'descriptor_master', 'corporate_announcement_category',
                          ['category_id'], ['id'])
    # op.alter_column('goaltracker', 'started_at',
    #            existing_type=sa.Date(),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # op.alter_column('goaltracker', 'ended_at',
    #            existing_type=sa.Date(),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_bse_id_fkey', 'notification', type_='foreignkey')
    op.drop_column('notification', 'bse_id')
    op.drop_constraint(None, 'corporate_announcement', type_='foreignkey')
    op.drop_column('corporate_announcement', 'category_id')
    op.drop_constraint(None, 'bse_corp_feed', type_='foreignkey')
    op.drop_constraint(None, 'bse_corp_feed', type_='foreignkey')
    op.drop_constraint(None, 'descriptor_master', type_='foreignkey')
    op.drop_column('bse_corp_feed', 'ec_category')
    op.drop_column('bse_corp_feed', 'account_id')
    op.drop_column('descriptor_master', 'category_id')
    # op.alter_column('goaltracker', 'ended_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.Date(),
    #            existing_nullable=False)
    # op.alter_column('goaltracker', 'started_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.Date(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
