"""empty message

Revision ID: 35d8058531e6
Revises: ce1957af2db4
Create Date: 2018-07-11 19:56:36.688368

"""
from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35d8058531e6'
down_revision = 'ce1957af2db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('cc_emails', postgresql.ARRAY(app.base.model_fields.LCString(length=128)), nullable=True))
    op.add_column('webcast', sa.Column('cc_emails', postgresql.ARRAY(app.base.model_fields.LCString(length=128)), nullable=True))
    op.add_column('webinar', sa.Column('cc_emails', postgresql.ARRAY(app.base.model_fields.LCString(length=128)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar', 'cc_emails')
    op.drop_column('webcast', 'cc_emails')
    op.drop_column('survey', 'cc_emails')
    # ### end Alembic commands ###
