"""empty message

Revision ID: 364aadd63031
Revises: ac58c4ecbabc
Create Date: 2018-06-01 13:22:51.046576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364aadd63031'
down_revision = 'ac58c4ecbabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast', sa.Column('cancelled', sa.Boolean(), nullable=True))
    op.execute("UPDATE webcast SET cancelled=false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webcast', 'cancelled')
    # ### end Alembic commands ###
