"""empty message

Revision ID: 3836b0ddda42
Revises: 6fabbdc11061
Create Date: 2021-11-18 19:12:56.420624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision = '3836b0ddda42'
down_revision = 'dff90b7b2963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_transcribe',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('email', app.base.model_fields.LCString(length=128), nullable=False),
    sa.Column('progress', app.base.model_fields.ChoiceString(app.resources.audio_transcribe.constants.AT_PROGRESS_TYPE_CHOICES), nullable=False),
    sa.Column('err_msg', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_transcribe')
    # ### end Alembic commands ###
