"""empty message

Revision ID: 38e7eee80c94
Revises: ad732cfdad89
Create Date: 2018-12-04 13:27:58.921376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38e7eee80c94'
down_revision = 'b0641c131cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar', sa.Column('open_to_public', sa.Boolean(), nullable=True))
    op.execute("UPDATE webinar SET open_to_public=false")
    op.add_column('webinar_invitee',
                  sa.Column('invitee_company', sa.String(length=256),
                            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar', 'open_to_public')
    op.drop_column('webinar_invitee', 'invitee_company')
    # ### end Alembic commands ###
