"""empty message

Revision ID: 398cd5e31ec7
Revises: 40f19727b950
Create Date: 2021-11-12 17:03:00.878069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398cd5e31ec7'
down_revision = '40f19727b950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_announcement', sa.Column('result_date', sa.DateTime(), nullable=True))
    op.add_column('result_tracker_group_companies', sa.Column('announcement_id', sa.BigInteger(), nullable=False))
    op.add_column('result_tracker_group_companies', sa.Column('result_url', sa.String(length=256), nullable=True))
    op.create_foreign_key('result_tracker_cannouncement_id_fkey', 'result_tracker_group_companies', 'corporate_announcement', ['announcement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_tracker_cannouncement_id_fkey', 'result_tracker_group_companies', type_='foreignkey')
    op.drop_column('result_tracker_group_companies', 'result_url')
    op.drop_column('result_tracker_group_companies', 'announcement_id')
    op.drop_column('corporate_announcement', 'result_date')
    # ### end Alembic commands ###
