"""empty message

Revision ID: 3af0364f0ecf
Revises: 59d3dc7dcb84
Create Date: 2019-06-19 15:53:02.671859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3af0364f0ecf'
# down_revision = 'ac2a409a8d0c'
down_revision = 'ad2de29b2eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_sme', sa.Boolean(), nullable=True))
    op.add_column('account_profile', sa.Column('shares', sa.String(length=128), nullable=True))
    op.add_column('account_profile', sa.Column('stock_price', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_profile', 'stock_price')
    op.drop_column('account_profile', 'shares')
    op.drop_column('account', 'is_sme')
    # ### end Alembic commands ###
