"""empty message

Revision ID: 3af9dee0bd41
Revises: cd02c97a1a8e
Create Date: 2018-09-24 18:46:00.605470

"""
from alembic import op
import sqlalchemy as sa

import app


# revision identifiers, used by Alembic.
revision = '3af9dee0bd41'
down_revision = '519eda76c617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_open_meeting', sa.Column('account_type_preference', sa.ARRAY(app.base.model_fields.ChoiceString(app.resources.accounts.constants.ACCT_TYPES_CHOICES)), nullable=True))
    op.add_column('ca_open_meeting', sa.Column('designation_preference', sa.ARRAY(app.base.model_fields.ChoiceString(app.resources.designations.constants.DES_LEVEL_TYPES_CHOICES)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_open_meeting', 'designation_preference')
    op.drop_column('ca_open_meeting', 'account_type_preference')
    # ### end Alembic commands ###
