"""empty message

Revision ID: 3dcb19d384df
Revises: 34f2c79de81e
Create Date: 2020-12-23 12:13:03.759261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dcb19d384df'
down_revision = '642d733c0477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.create_table('activityfile',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='activityfile_activity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['archive_file.id'], name='activityfile_file_id_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('activity_id', 'file_id', name='ac_activity_id_file_id_key')
    )"""

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activityfile')
    # ### end Alembic commands ###