"""empty message

Revision ID: 40f19727b950
Revises: 7027c00174ba
Create Date: 2021-11-11 19:53:44.853600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f19727b950'
down_revision = '7027c00174ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('result_tracker_group_id_account_id_deleted_user_id_uniquekey', 'result_tracker_group_companies', ['group_id', 'account_id', 'deleted', 'user_id'])
    op.drop_constraint('result_tracker_group_id_account_id_deleted_uniquekey', 'result_tracker_group_companies', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('result_tracker_group_id_account_id_deleted_uniquekey', 'result_tracker_group_companies', ['group_id', 'account_id', 'deleted'])
    op.drop_constraint('result_tracker_group_id_account_id_deleted_user_id_uniquekey', 'result_tracker_group_companies', type_='unique')
    # ### end Alembic commands ###
