"""empty message

Revision ID: 4a05cb9bd1f9
Revises: 8555dba5a3c7
Create Date: 2018-07-26 13:21:54.708893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a05cb9bd1f9'
down_revision = '8555dba5a3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_open_meeting', sa.Column('alternative_dial_in_detail', sa.String(length=512), nullable=True))
    op.add_column('ca_open_meeting', sa.Column('dial_in_detail', sa.String(length=128), nullable=True))
    op.add_column('ca_open_meeting', sa.Column('is_converted', sa.Boolean(), nullable=True))
    op.execute("UPDATE ca_open_meeting SET is_converted=false")
    op.add_column('corporate_access_event', sa.Column('is_open_meeting', sa.Boolean(), nullable=True))
    op.execute("UPDATE corporate_access_event SET is_open_meeting=false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event', 'is_open_meeting')
    op.drop_column('ca_open_meeting', 'is_converted')
    op.drop_column('ca_open_meeting', 'dial_in_detail')
    op.drop_column('ca_open_meeting', 'alternative_dial_in_detail')
    # ### end Alembic commands ###
