"""empty message

Revision ID: 4ccb04ef3b7c
Revises: a35303ee29f1
Create Date: 2018-11-19 12:48:36.201185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccb04ef3b7c'
down_revision = 'a35303ee29f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('is_crm_contact', sa.Boolean(), nullable=True))

    op.add_column('crm_contact', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.alter_column('crm_contact', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_foreign_key('crm_contact_user_id_fkey', 'crm_contact', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('crmcontactfiles')
    op.add_column('crm_library_file',
                  sa.Column('title', sa.String(length=256), nullable=True))
    op.add_column('crm_library_file',
                  sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('crm_library_file_user_id_fkey', 'crm_library_file',
                          'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crm_contact_user_id_fkey', 'crm_contact', type_='foreignkey')
    op.alter_column('crm_contact', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('crm_contact', 'user_id')
    op.drop_constraint('crm_library_file_user_id_fkey', 'crm_library_file',
                       type_='foreignkey')
    op.drop_column('crm_library_file', 'user_id')
    op.drop_column('crm_library_file', 'title')
    op.create_table('crmcontactfiles',
                    sa.Column('crm_contact_id', sa.BIGINT(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_id', sa.INTEGER(), autoincrement=False,
                              nullable=False),
                    sa.ForeignKeyConstraint(['crm_contact_id'],
                                            ['crm_contact.id'],
                                            name='crmconatfiles_crm_contact_id_fkey',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['file_id'],
                                            ['crm_library_file.id'],
                                            name='crmconatfiles_file_id_fkey',
                                            ondelete='CASCADE'),
                    sa.UniqueConstraint('crm_contact_id', 'file_id',
                                        name='ac_crm_contact_id_file_id_key')
                    )
    op.drop_column('user', 'is_crm_contact')
    # ### end Alembic commands ###
