"""empty message

Revision ID: 4e76452fb4af
Revises: bdd4a7b62079
Create Date: 2019-10-18 13:02:33.472249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e76452fb4af'
down_revision = 'bdd4a7b62079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('domain_id', sa.BigInteger(),
                                       nullable=True))
    op.execute("update account_profile  set country = 'India' where country "
               "not in ('Hong Kong', 'China')")
    op.execute("update account set domain_id = case when p.country = 'India' "
               "then 1 else 2 end from account_profile p "
               "where p.account_id = account.id")
    op.execute("alter table account alter column domain_id set not null;")
    op.create_foreign_key('account_domain_id_fkey', 'account', 'domain',
                          ['domain_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('corporate_access_ref_event_sub_type_account_id_fkey',
                       'corporate_access_ref_event_sub_type',
                       type_='foreignkey')
    op.drop_column('corporate_access_ref_event_sub_type', 'account_id')
    op.execute("alter table corporate_access_ref_event_type drop column account_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('account_domain_id_fkey', 'account', type_='foreignkey')
    op.drop_column('account', 'domain_id')
    op.add_column('corporate_access_ref_event_sub_type',
                  sa.Column('account_id', sa.BIGINT(), autoincrement=False,
                            nullable=False))
    op.create_foreign_key(
        'corporate_access_ref_event_sub_type_account_id_fkey',
        'corporate_access_ref_event_sub_type', 'account', ['account_id'],
        ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
