"""empty message

Revision ID: 4ece8cbf3cf5
Revises: 2775da5ddcf4
Create Date: 2018-02-19 21:40:59.752045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ece8cbf3cf5'
down_revision = '2775da5ddcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_profile_account_id_fkey', 'account_profile', type_='foreignkey')
    op.create_foreign_key('account_profile_account_id_fkey', 'account_profile', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    op.alter_column('account_profile', 'account_id', type_=sa.BigInteger())
    op.create_unique_constraint('c_cracs_event_id_corporate_access_event_slot_id_attendee_id_key', 'corporate_access_event_attendee', ['corporate_access_event_id', 'corporate_access_event_slot_id', 'attendee_id'])
    op.drop_constraint('c_corporate_access_event_id_corporate_access_event_slot_id_atte', 'corporate_access_event_attendee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('c_corporate_access_event_id_corporate_access_event_slot_id_atte', 'corporate_access_event_attendee', ['corporate_access_event_id', 'corporate_access_event_slot_id', 'attendee_id'])
    op.drop_constraint('c_cracs_event_id_corporate_access_event_slot_id_attendee_id_key', 'corporate_access_event_attendee', type_='unique')
    op.drop_constraint('account_profile_account_id_fkey', 'account_profile', type_='foreignkey')
    op.create_foreign_key('account_profile_account_id_fkey', 'account_profile', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###
