"""empty message

Revision ID: 504c6e35bd49
Revises: abd58cf2da48
Create Date: 2018-06-12 20:21:07.090627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504c6e35bd49'
down_revision = 'abd58cf2da48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast_participant', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('c_webcast_id_sequence_id_key', 'webcast_participant', ['webcast_id', 'sequence_id'])
    op.add_column('webcast_rsvp', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('c_wbcnrp_webcast_id_sequence_id_key', 'webcast_rsvp', ['webcast_id', 'sequence_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('c_wbcnrp_webcast_id_sequence_id_key', 'webcast_rsvp', type_='unique')
    op.drop_column('webcast_rsvp', 'sequence_id')
    op.drop_constraint('c_webcast_id_sequence_id_key', 'webcast_participant', type_='unique')
    op.drop_column('webcast_participant', 'sequence_id')
    # ### end Alembic commands ###
