"""empty message

Revision ID: 52eab9b76f85
Revises: 9ac9ad71fc06
Create Date: 2018-03-07 12:33:18.548315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52eab9b76f85'
down_revision = '9ac9ad71fc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_time_zone',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('timezone_value', sa.String(length=128), nullable=True),
    sa.Column('offset', sa.String(length=32), nullable=True),
    sa.Column('display_value', sa.String(length=256), nullable=False),
    sa.Column('utc', postgresql.ARRAY(sa.String(length=256)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event_invite', sa.Column('comment', sa.String(length=1024), nullable=True))
    op.drop_constraint('event_type_name_key', 'event_type', type_='unique')
    op.create_index('ci_event_type_unique_name', 'event_type', [sa.text('lower(name)')], unique=True)
    op.create_index('ci_ref_time_zone_unique_display_value', 'ref_time_zone', [sa.text('lower(display_value)')], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('event_type_name_key', 'event_type', ['name'])
    op.drop_index('ci_event_type_unique_name')
    op.drop_column('event_invite', 'comment')
    op.drop_table('ref_time_zone')
    # ### end Alembic commands ###
