"""empty message

Revision ID: 551bdfcfb445
Revises: 8789975752bd
Create Date: 2018-06-30 12:21:34.238009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551bdfcfb445'
down_revision = '8789975752bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_response', sa.Column('designation', sa.String(length=128), nullable=True))
    op.add_column('survey_response', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('survey_response', sa.Column('last_name', sa.String(length=128), nullable=True))
    op.drop_column('survey_response', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_response', sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('survey_response', 'last_name')
    op.drop_column('survey_response', 'first_name')
    op.drop_column('survey_response', 'designation')
    # ### end Alembic commands ###
