"""empty message

Revision ID: 56c7cbd8ea34
Revises: 1c8d6c06f588
Create Date: 2019-04-17 13:21:19.350812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56c7cbd8ea34'
down_revision = '1c8d6c06f588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_contact', 'alternet_phone_number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('crm_contact', 'phone_number',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('user_profile', 'phone_number',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('crm_contact', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('crm_contact', 'alternet_phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
