"""empty message

Revision ID: 57e2adb64c67
Revises: 77c1ab448228
Create Date: 2020-12-05 13:41:02.961871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision = '57e2adb64c67'
down_revision = '77c1ab448228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.create_table('activity_institution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('account_name', sa.String(length=256), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('factset_entity_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='institute_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='institute_activity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_institution_participant',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_name', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='institute_participant_activity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], name='institution_contact_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name='institution_participant_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_organiser',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('account_name', sa.String(length=256), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='organiser_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='organiser_activity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_organiser_participant',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_name', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='organiser_participant_activity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], name='organiser_contact_d_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name='organiser_participant_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_representative',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='representative_activity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contact.id'], name='representative_contact_d_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name='representative_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('account', 'facebook_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('account', 'linkedin_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('account', 'twitter_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.add_column('activity', sa.Column('account_type', app.base.model_fields.ChoiceString(app.activity.activities.constants.AC_TYPES_CHOICE), nullable=True))
    op.add_column('activity', sa.Column('meeting_url', sa.String(length=256), nullable=True))
    op.alter_column('corporate_access_event_invitee', 'invitee_company',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.create_foreign_key('e_meeting_comment_id_fkey', 'e_meeting_comment', 'e_meeting', ['e_meeting_id'], ['id'], ondelete='CASCADE')
    op.alter_column('news_item', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('project', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('reminder_activity_id_fkey', 'reminder', type_='foreignkey')
    op.drop_constraint('reminder_user_id_fkey', 'reminder', type_='foreignkey')
    op.create_foreign_key('reminder_user_id_fkey', 'reminder', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reminder_activity_id_fkey', 'reminder', 'activity', ['activity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_menu_permissions_menu_id_fkey', 'role_menu_permissions', 'menu', ['menu_id'], ['id'], ondelete='CASCADE')"""
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_menu_permissions_menu_id_fkey', 'role_menu_permissions', type_='foreignkey')
    op.drop_constraint('reminder_activity_id_fkey', 'reminder', type_='foreignkey')
    op.drop_constraint('reminder_user_id_fkey', 'reminder', type_='foreignkey')
    op.create_foreign_key('reminder_user_id_fkey', 'reminder', 'user', ['user_id'], ['id'])
    op.create_foreign_key('reminder_activity_id_fkey', 'reminder', 'activity', ['activity_id'], ['id'])
    op.alter_column('project', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('news_item', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_constraint('e_meeting_comment_id_fkey', 'e_meeting_comment', type_='foreignkey')
    op.alter_column('corporate_access_event_invitee', 'invitee_company',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.drop_column('activity', 'meeting_url')
    op.drop_column('activity', 'account_type')
    op.alter_column('account', 'twitter_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('account', 'linkedin_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('account', 'facebook_id',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('activity_representative')
    op.drop_table('activity_organiser_participant')
    op.drop_table('activity_organiser')
    op.drop_table('activity_institution_participant')
    op.drop_table('activity_institution')
    # ### end Alembic commands ###