"""empty message

Revision ID: 5b479528a506
Revises: a111bc13966f
Create Date: 2021-09-30 14:35:36.090301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b479528a506'
down_revision = 'e39a711d4bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_analyst_comment', sa.Column('subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_analyst_comment', 'subject')
    # ### end Alembic commands ###
