"""empty message

Revision ID: 642d733c0477
Revises: 28926377d629
Create Date: 2020-12-09 13:28:38.172701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '642d733c0477'
down_revision = '57e2adb64c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.create_table('favirmodule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('ir_module_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ir_module_id'], ['ir_module.id'], name='fav_ir_module_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fav_ir_module_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ir_module_id', 'user_id', name='fav_ir_module_user_id_key')
    )
    op.add_column('ir_module', sa.Column('infoghraphic_url', sa.String(), nullable=True))
    op.add_column('ir_module', sa.Column('profile_thumbnail_url', sa.String(), nullable=True))
    op.drop_column('ir_module', 'favourite')
    op.add_column('ir_module_heading', sa.Column('deactivated', sa.Boolean(), nullable=True))
    op.alter_column('ir_module_heading', 'description',
               existing_type=sa.VARCHAR(length=9216),
               type_=sa.String(),
               existing_nullable=True)"""
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ir_module_heading', 'deactivated')
    op.add_column('ir_module', sa.Column('favourite', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('ir_module', 'profile_thumbnail_url')
    op.drop_column('ir_module', 'infoghraphic_url')
    op.drop_table('favirmodule')
    op.alter_column('ir_module_heading', 'description',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=9216),
               existing_nullable=True)
    # ### end Alembic commands ###