"""empty message

Revision ID: 653ab361dc49
Revises: 9dbeb508c2e2
Create Date: 2019-08-31 05:22:27.597875

"""
from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '653ab361dc49'
down_revision = '1e91172e3671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('bse_symbol', sa.String(length=32), nullable=True))
    op.add_column('account', sa.Column('fsym_id', sa.String(length=128), nullable=True))
    op.add_column('account', sa.Column('nse_symbol', sa.String(length=32), nullable=True))
    op.add_column('account', sa.Column('perm_security_id', sa.String(length=128), nullable=True))
    # op.add_column('account', sa.Column('ec_identifier', sa.String(length=128), nullable=True))
    op.add_column('account', sa.Column('website', sa.String(length=512), nullable=True))
    op.add_column('management_profile', sa.Column('email', app.base.model_fields.LCString(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('management_profile', 'email')
    op.drop_column('account', 'website')
    # op.drop_column('account', 'ec_identifier')
    op.drop_column('account', 'perm_security_id')
    op.drop_column('account', 'nse_symbol')
    op.drop_column('account', 'fsym_id')
    op.drop_column('account', 'bse_symbol')
    # ### end Alembic commands ###
