"""empty message

Revision ID: 67bdae182cad
Revises: da1cb0e9224c
Create Date: 2019-11-18 14:37:19.744081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67bdae182cad'
down_revision = 'da1cb0e9224c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('currency', sa.String(length=32), nullable=True))
    op.add_column('domain', sa.Column('google_address_code', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'domain', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('domain', 'google_address_code')
    op.drop_column('domain', 'currency')
    op.create_unique_constraint(None, 'domain', ['name'])

    # ### end Alembic commands ###
