"""empty message

Revision ID: 6997213417e6
Revises: 6ad729f45c4b
Create Date: 2018-04-16 17:09:45.874500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6997213417e6'
down_revision = '6ad729f45c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.add_column('account', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
    op.add_column('company', sa.Column('industry_id', sa.BigInteger(), nullable=True))
    op.alter_column('company', 'industry', new_column_name='industry_name')
    op.add_column('company', sa.Column('sector_id', sa.BigInteger(), nullable=True))
    op.alter_column('company', 'sector', new_column_name='sector_name')
    op.create_foreign_key('company_industry_id_fkey', 'company', 'industry', ['industry_id'], ['id'])
    op.create_foreign_key('company_sector_id_fkey', 'company', 'sector', ['sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_sector_id_fkey', 'company', type_='foreignkey')
    op.drop_constraint('company_industry_id_fkey', 'company', type_='foreignkey')
    op.alter_column('company', 'sector_name', new_column_name='sector')
    op.drop_column('company', 'sector_id')
    op.alter_column('company', 'industry_name', new_column_name='industry')
    op.drop_column('company', 'industry_id')
    op.drop_column('account', 'subscription_start_date')
    op.drop_column('account', 'subscription_end_date')
    op.drop_column('account', 'is_trial')
    # ### end Alembic commands ###
