"""empty message

Revision ID: 6ad729f45c4b
Revises: 10a13940e931
Create Date: 2018-04-16 12:38:56.650651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad729f45c4b'
down_revision = '10a13940e931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('activation_date', sa.DateTime(), nullable=True))
    op.add_column('management_profile', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('management_profile_user_id_fkey', 'management_profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('management_profile_user_id_fkey', 'management_profile', type_='foreignkey')
    op.drop_column('management_profile', 'user_id')
    op.drop_column('account', 'activation_date')
    # ### end Alembic commands ###
