"""empty message

Revision ID: 6b674a1ef38a
Revises: 7dcb034ea12a
Create Date: 2021-11-10 19:48:59.202801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b674a1ef38a'
down_revision = '7dcb034ea12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_tracker_group_id_account_id_uniquekey', 'result_tracker_group_companies', type_='unique')
    op.create_unique_constraint('result_tracker_group_id_account_id_uniquekey', 'result_tracker_group_companies', ['group_id', 'account_id', 'deleted'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_tracker_group_id_account_id_uniquekey', 'result_tracker_group_companies', type_='unique')
    op.create_unique_constraint('result_tracker_group_id_account_id_uniquekey', 'result_tracker_group_companies', ['group_id', 'account_id'])
    # ### end Alembic commands ###
