"""empty message

Revision ID: 6f70030f8c08
Revises: f90e11faba65
Create Date: 2018-07-23 13:39:39.835605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f70030f8c08'
down_revision = 'f90e11faba65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('ca_open_meeting_id', sa.BigInteger(), nullable=True))
    op.add_column('notification', sa.Column('ca_open_meeting_inquiry_id', sa.BigInteger(), nullable=True))
    op.add_column('notification', sa.Column('ca_open_meeting_slot_id', sa.BigInteger(), nullable=True))
    op.add_column('notification', sa.Column('caom_slot_name', sa.String(length=256), nullable=True))
    op.create_foreign_key('notification_ca_open_meeting_slot_id_fkey', 'notification', 'ca_open_meeting_slot', ['ca_open_meeting_slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notification_ca_open_meeting_inquiry_id_fkey', 'notification', 'ca_open_meeting_inquiry', ['ca_open_meeting_inquiry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notification_ca_open_meeting_id_fkey', 'notification', 'ca_open_meeting', ['ca_open_meeting_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_ca_open_meeting_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_ca_open_meeting_inquiry_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_ca_open_meeting_slot_id_fkey', 'notification', type_='foreignkey')
    op.drop_column('notification', 'caom_slot_name')
    op.drop_column('notification', 'ca_open_meeting_slot_id')
    op.drop_column('notification', 'ca_open_meeting_inquiry_id')
    op.drop_column('notification', 'ca_open_meeting_id')
    # ### end Alembic commands ###
