"""empty message

Revision ID: 70a96bc7c85d
Revises: d8293404401e
Create Date: 2018-03-21 12:39:40.266329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a96bc7c85d'
down_revision = 'd8293404401e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('c_created_by_corpacc_event_id_invitee_id_invitee_email_key', 'corporate_access_event_invitee', ['created_by', 'corporate_access_event_id', 'invitee_id', 'invitee_email'])
    op.drop_constraint('c_corporate_access_event_id_invitee_id_invitee_email_key', 'corporate_access_event_invitee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('c_corporate_access_event_id_invitee_id_invitee_email_key', 'corporate_access_event_invitee', ['corporate_access_event_id', 'invitee_id', 'invitee_email'])
    op.drop_constraint('c_created_by_corpacc_event_id_invitee_id_invitee_email_key', 'corporate_access_event_invitee', type_='unique')
    # ### end Alembic commands ###
