"""empty message

Revision ID: 7520c0ec73c9
Revises: 873814a9213d
Create Date: 2018-03-19 15:14:00.211925

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = '7520c0ec73c9'
down_revision = '873814a9213d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_invitee', sa.Column('invitee_first_name', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event_invitee', sa.Column('invitee_last_name', sa.String(length=128), nullable=True))
    op.drop_constraint('corporate_access_event_invitee_invitee_id_fkey', 'corporate_access_event_invitee', type_='foreignkey')
    op.create_foreign_key('corporate_access_event_invitee_invitee_id_fkey', 'corporate_access_event_invitee', 'user', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('c_check_invitee_id_invitee_email_not_all_null_key', 'corporate_access_event_invitee', type_='check')
    op.create_check_constraint('c_check_caei_invitee_id_invitee_email_not_all_null_key', 'corporate_access_event_invitee', '((invitee_id IS NOT NULL) OR (invitee_email IS NOT NULL))')

    op.add_column('corporate_access_event_participant', sa.Column('participant_email', app.base.model_fields.LCString(length=128), nullable=True))
    op.add_column('corporate_access_event_participant', sa.Column('participant_first_name', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event_participant', sa.Column('participant_last_name', sa.String(length=128), nullable=True))
    op.alter_column('corporate_access_event_participant', 'participant_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint('c_corp_access_evt_id_participant_id_participant_email_key', 'corporate_access_event_participant', ['corporate_access_event_id', 'participant_id', 'participant_email'])
    op.drop_constraint('c_corporate_access_event_id_participant_id_key', 'corporate_access_event_participant', type_='unique')
    op.create_check_constraint('c_check_caep_participant_id_participant_email_not_all_null_key', 'corporate_access_event_participant', '((participant_id IS NOT NULL) OR (participant_email IS NOT NULL))')

    op.add_column('webcast_invitee', sa.Column('invitee_first_name', sa.String(length=128), nullable=True))
    op.add_column('webcast_invitee', sa.Column('invitee_last_name', sa.String(length=128), nullable=True))
    op.drop_constraint('webcast_invitee_invitee_id_fkey', 'webcast_invitee', type_='foreignkey')
    op.create_foreign_key('webcast_invitee_invitee_id_fkey', 'webcast_invitee', 'user', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('c_check_invitee_id_invitee_email_not_all_null_key', 'webcast_invitee', type_='check')
    op.create_check_constraint('c_check_wbcinv_invitee_id_invitee_email_not_all_null_key', 'webcast_invitee', '((invitee_id IS NOT NULL) OR (invitee_email IS NOT NULL))')

    op.add_column('webcast_participant', sa.Column('participant_email', app.base.model_fields.LCString(length=128), nullable=True))
    op.add_column('webcast_participant', sa.Column('participant_first_name', sa.String(length=128), nullable=True))
    op.add_column('webcast_participant', sa.Column('participant_last_name', sa.String(length=128), nullable=True))
    op.alter_column('webcast_participant', 'participant_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint('c_webcast_id_participant_id_participant_email_key', 'webcast_participant', ['webcast_id', 'participant_id', 'participant_email'])
    op.drop_constraint('c_webcast_id_participant_id_key', 'webcast_participant', type_='unique')
    op.create_check_constraint('c_check_wbcpr_participant_id_participant_email_not_all_null_key', 'webcast_participant', '((participant_id IS NOT NULL) OR (participant_email IS NOT NULL))')

    op.add_column('webinar_invitee', sa.Column('invitee_first_name', sa.String(length=128), nullable=True))
    op.add_column('webinar_invitee', sa.Column('invitee_last_name', sa.String(length=128), nullable=True))
    op.drop_constraint('webinar_invitee_invitee_id_fkey', 'webinar_invitee', type_='foreignkey')
    op.create_foreign_key('webinar_invitee_invitee_id_fkey', 'webinar_invitee', 'user', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('c_check_invitee_id_invitee_email_not_all_null_key', 'webinar_invitee', type_='check')
    op.create_check_constraint('c_check_wbninv_invitee_id_invitee_email_not_all_null_key', 'webinar_invitee', '((invitee_id IS NOT NULL) OR (invitee_email IS NOT NULL))')

    op.add_column('webinar_participant', sa.Column('participant_email', app.base.model_fields.LCString(length=128), nullable=True))
    op.add_column('webinar_participant', sa.Column('participant_first_name', sa.String(length=128), nullable=True))
    op.add_column('webinar_participant', sa.Column('participant_last_name', sa.String(length=128), nullable=True))
    op.alter_column('webinar_participant', 'participant_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint('c_webinar_id_participant_id_participant_email_key', 'webinar_participant', ['webinar_id', 'participant_id', 'participant_email'])
    op.drop_constraint('c_webinar_id_participant_id_key', 'webinar_participant', type_='unique')
    op.create_check_constraint('c_check_wbnpr_participant_id_participant_email_not_all_null_key', 'webinar_participant', '((participant_id IS NOT NULL) OR (participant_email IS NOT NULL))')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('c_webinar_id_participant_id_key', 'webinar_participant', ['webinar_id', 'participant_id'])
    op.drop_constraint('c_webinar_id_participant_id_participant_email_key', 'webinar_participant', type_='unique')
    op.alter_column('webinar_participant', 'participant_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('c_check_wbnpr_participant_id_participant_email_not_all_null_key', 'webinar_participant', type_='check')
    op.drop_column('webinar_participant', 'participant_last_name')
    op.drop_column('webinar_participant', 'participant_first_name')
    op.drop_column('webinar_participant', 'participant_email')

    op.drop_constraint('webinar_invitee_invitee_id_fkey', 'webinar_invitee', type_='foreignkey')
    op.create_foreign_key('webinar_invitee_invitee_id_fkey', 'webinar_invitee', 'user', ['invitee_id'], ['id'])
    op.drop_column('webinar_invitee', 'invitee_last_name')
    op.drop_column('webinar_invitee', 'invitee_first_name')
    op.drop_constraint('c_check_wbninv_invitee_id_invitee_email_not_all_null_key', 'webinar_invitee', type_='check')
    op.create_check_constraint('c_check_invitee_id_invitee_email_not_all_null_key', 'webinar_invitee', '((invitee_id IS NOT NULL) OR (invitee_email IS NOT NULL))')

    op.create_unique_constraint('c_webcast_id_participant_id_key', 'webcast_participant', ['webcast_id', 'participant_id'])
    op.drop_constraint('c_webcast_id_participant_id_participant_email_key', 'webcast_participant', type_='unique')
    op.alter_column('webcast_participant', 'participant_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('c_check_wbcpr_participant_id_participant_email_not_all_null_key', 'webcast_participant', type_='check')
    op.drop_column('webcast_participant', 'participant_last_name')
    op.drop_column('webcast_participant', 'participant_first_name')
    op.drop_column('webcast_participant', 'participant_email')

    op.drop_constraint('webcast_invitee_invitee_id_fkey', 'webcast_invitee', type_='foreignkey')
    op.create_foreign_key('webcast_invitee_invitee_id_fkey', 'webcast_invitee', 'user', ['invitee_id'], ['id'])
    op.drop_column('webcast_invitee', 'invitee_last_name')
    op.drop_column('webcast_invitee', 'invitee_first_name')
    op.drop_constraint('c_check_wbcinv_invitee_id_invitee_email_not_all_null_key', 'webcast_invitee', type_='check')
    op.create_check_constraint('c_check_invitee_id_invitee_email_not_all_null_key', 'webcast_invitee', '((invitee_id IS NOT NULL) OR (invitee_email IS NOT NULL))')

    op.create_unique_constraint('c_corporate_access_event_id_participant_id_key', 'corporate_access_event_participant', ['corporate_access_event_id', 'participant_id'])
    op.drop_constraint('c_corp_access_evt_id_participant_id_participant_email_key', 'corporate_access_event_participant', type_='unique')
    op.alter_column('corporate_access_event_participant', 'participant_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('c_check_caep_participant_id_participant_email_not_all_null_key', 'corporate_access_event_participant', type_='check')
    op.drop_column('corporate_access_event_participant', 'participant_last_name')
    op.drop_column('corporate_access_event_participant', 'participant_first_name')
    op.drop_column('corporate_access_event_participant', 'participant_email')

    op.drop_constraint('corporate_access_event_invitee_invitee_id_fkey', 'corporate_access_event_invitee', type_='foreignkey')
    op.create_foreign_key('corporate_access_event_invitee_invitee_id_fkey', 'corporate_access_event_invitee', 'user', ['invitee_id'], ['id'])
    op.drop_column('corporate_access_event_invitee', 'invitee_last_name')
    op.drop_column('corporate_access_event_invitee', 'invitee_first_name')
    op.drop_constraint('c_check_caei_invitee_id_invitee_email_not_all_null_key', 'corporate_access_event_invitee', type_='check')
    op.create_check_constraint('c_check_invitee_id_invitee_email_not_all_null_key', 'corporate_access_event_invitee', '((invitee_id IS NOT NULL) OR (invitee_email IS NOT NULL))')
    # ### end Alembic commands ###
