"""empty message

Revision ID: 7603041c70f0
Revises: ac0cb89b79b9
Create Date: 2020-04-02 14:32:25.214373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7603041c70f0'
down_revision = 'ac0cb89b79b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_announcement_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('subject_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('category_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.execute(
        "insert into corporate_announcement_category (created_date, modified_date, "
        "name, created_by, updated_by, deleted, subject_keywords, category_keywords) values("
        "current_timestamp, current_timestamp, 'annual reports',  1, 1, '0', "
        "'{""Annual Reports"",""Annual Report""}','{""Annual Reports"",""Annual Report""}')")
    op.execute(
        "insert into corporate_announcement_category (created_date, modified_date, "
        "name, created_by, updated_by, deleted, subject_keywords) values("
        "current_timestamp, current_timestamp, 'concall transcripts',  1, 1, '0','{""Transcript""}')")
    op.execute(
        "insert into corporate_announcement_category (created_date, modified_date, "
        "name, created_by, updated_by, deleted, subject_keywords) values("
        "current_timestamp, current_timestamp, 'presentation',  1, 1, '0','{""Presentation""}')")
    op.execute(
        "insert into corporate_announcement_category (created_date, modified_date, "
        "name, created_by, updated_by, deleted, category_keywords) values("
        "current_timestamp, current_timestamp, 'result updates',  1, 1, '0','{""Result"", ""Outcome of Board Meeting"", ""Results""}')")
    op.execute(
        "insert into corporate_announcement_category (created_date, modified_date, "
        "name, created_by, updated_by, deleted) values("
        "current_timestamp, current_timestamp, 'news',  1, 1, '0')")
    op.execute(
        "insert into corporate_announcement_category (created_date, modified_date, "
        "name, created_by, updated_by, deleted) values("
        "current_timestamp, current_timestamp, 'others',  1, 1, '0')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('corporate_announcement_category')
    # ### end Alembic commands ###
