"""empty message

Revision ID: 77c1ab448228
Revises: bc77f43154f1
Create Date: 2020-11-09 12:09:28.777254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77c1ab448228'
down_revision = 'bc77f43154f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('notification', sa.Column('activity_id', sa.BigInteger(), nullable=True))
    #op.create_foreign_key('notification_activity_id_fkey', 'notification', 'activity', ['activity_id'], ['id'], ondelete='CASCADE')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_activity_id_fkey', 'notification', type_='foreignkey')
    op.drop_column('notification', 'activity_id')
    # ### end Alembic commands ###
