"""empty message

Revision ID: 7b9045d92065
Revises: 8646fb6cd20f
Create Date: 2018-02-22 19:57:10.774115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9045d92065'
down_revision = '8646fb6cd20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_item', sa.Column('post_date', sa.DateTime(), nullable=False))
    op.add_column('feed_item', sa.Column('poster_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key('feed_item_poster_id_fkey', 'feed_item', 'user', ['poster_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feed_item_poster_id_fkey', 'feed_item', type_='foreignkey')
    op.drop_column('feed_item', 'poster_id')
    op.drop_column('feed_item', 'post_date')
    # ### end Alembic commands ###
