"""empty message

Revision ID: 7dcb034ea12a
Revises: 29848d561ab2
Create Date: 2021-11-10 19:28:21.516775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcb034ea12a'
down_revision = '270757dc93ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_tracker_user_id_group_name_uniquekey', 'result_tracker_group', type_='unique')
    op.create_unique_constraint('result_tracker_user_id_group_name_uniquekey', 'result_tracker_group', ['user_id', 'group_name', 'deleted'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_tracker_user_id_group_name_uniquekey', 'result_tracker_group', type_='unique')
    op.create_unique_constraint('result_tracker_user_id_group_name_uniquekey', 'result_tracker_group', ['user_id', 'group_name'])
    # ### end Alembic commands ###
