"""empty message

Revision ID: 82b285f69d3b
Revises: 53e0d3ba9436
Create Date: 2021-09-07 14:23:30.117869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b285f69d3b'
down_revision = 'e776b8f37a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descriptor_master',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('descriptor_id', sa.Integer(), nullable=True),
    sa.Column('descriptor_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bsefeedaccounts',
    sa.Column('feed_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='bsefeedaccounts_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_id'], ['bse_corp_feed.id'], name='bsefeedaccounts_feed_id_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('feed_id', 'account_id', name='ac_feed_id_account_id_key')
    )
    op.add_column('bse_corp_feed', sa.Column('exchange_category', sa.String(), nullable=True))
    op.add_column('corporate_announcement', sa.Column('bse_descriptor', sa.BigInteger(), nullable=True))
    op.add_column('corporate_announcement', sa.Column('bse_type_of_announce', sa.String(), nullable=True))
    op.add_column('corporate_announcement', sa.Column('source', sa.String(), nullable=True))
    op.create_foreign_key('fk_bse_descriptor_id', 'corporate_announcement', 'descriptor_master', ['bse_descriptor'], ['id'])
    op.add_column('corporate_announcement_category', sa.Column('bse_keywords', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_announcement_category', 'bse_keywords')
    op.drop_constraint('fk_bse_descriptor_id', 'corporate_announcement', type_='foreignkey')
    op.drop_column('corporate_announcement', 'source')
    op.drop_column('corporate_announcement', 'bse_type_of_announce')
    op.drop_column('corporate_announcement', 'bse_descriptor')
    op.drop_column('bse_corp_feed', 'exchange_category')
    op.drop_table('bsefeedaccounts')
    op.drop_table('descriptor_master')
    # ### end Alembic commands ###
