"""empty message

Revision ID: 82d8e2c51fa5
Revises: b33460baff13
Create Date: 2021-11-23 15:44:53.977750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d8e2c51fa5'
down_revision = 'b33460baff13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_master_fkey', 'result_tracker_group_companies', type_='foreignkey')
    op.drop_column('result_tracker_group_companies', 'result_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result_tracker_group_companies', sa.Column('result_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('result_master_fkey', 'result_tracker_group_companies', 'result_master', ['result_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
