"""empty message

Revision ID: 8429068a8413
Revises: 27c4708b7d78
Create Date: 2018-03-28 21:39:17.413145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8429068a8413'
down_revision = '27c4708b7d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('corporate_access_event_id', sa.BigInteger(), nullable=True))
    op.add_column('notification', sa.Column('webcast_id', sa.BigInteger(), nullable=True))
    op.add_column('notification', sa.Column('webinar_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('notification_corporate_access_event_id_fkey', 'notification', 'corporate_access_event', ['corporate_access_event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notification_webinar_id_fkey', 'notification', 'webinar', ['webinar_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notification_webcast_id_fkey', 'notification', 'webcast', ['webcast_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_webcast_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_webinar_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_corporate_access_event_id_fkey', 'notification', type_='foreignkey')
    op.drop_column('notification', 'webinar_id')
    op.drop_column('notification', 'webcast_id')
    op.drop_column('notification', 'corporate_access_event_id')
    # ### end Alembic commands ###
