"""empty message

Revision ID: 8535b1dca515
Revises: 7520c0ec73c9
Create Date: 2018-03-20 12:08:11.951126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8535b1dca515'
down_revision = '7520c0ec73c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('c_event_id_slot_id_created_by_key', 'corporate_access_event_inquiry', ['created_by', 'corporate_access_event_id', 'corporate_access_event_slot_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('c_event_id_slot_id_created_by_key', 'corporate_access_event_inquiry', type_='unique')
    # ### end Alembic commands ###
