"""empty message

Revision ID: 8555dba5a3c7
Revises: 6f70030f8c08
Create Date: 2018-07-25 15:39:17.027018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8555dba5a3c7'
down_revision = '6f70030f8c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('updated_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key('contact_us_updated_by_fkey', 'contact_us', 'user', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_us_updated_by_fkey', 'contact_us', type_='foreignkey')
    op.drop_column('contact_us', 'updated_by')
    # ### end Alembic commands ###
