"""empty message

Revision ID: 8646fb6cd20f
Revises: e3fc21c53e56
Create Date: 2018-02-22 14:37:20.107655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8646fb6cd20f'
down_revision = 'e3fc21c53e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast_setting', sa.Column('completion_message', sa.String(length=512), nullable=True))
    op.drop_column('webcast_setting', 'completion_mesage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast_setting', sa.Column('completion_mesage', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('webcast_setting', 'completion_message')
    # ### end Alembic commands ###
