"""empty message

Revision ID: 8789975752bd
Revises: 4a4df02cbfec
Create Date: 2018-06-19 15:44:02.054658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8789975752bd'
down_revision = '4a4df02cbfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event', sa.Column('attachment', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event', 'attachment')
    # ### end Alembic commands ###
