"""empty message

Revision ID: 87f59537eb11
Revises: 7bceb17f910e
Create Date: 2020-08-19 12:15:30.393825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87f59537eb11'
down_revision = '0207bc5e3a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_analyst_comment', sa.Column('domain_id', sa.BigInteger(), nullable=True))
    # op.alter_column('market_analyst_comment', 'domain_id', nullable=False)
    op.create_foreign_key('market_comment_domain_id_fkey', 'market_analyst_comment', 'domain', ['domain_id'], ['id'])
    op.execute("UPDATE market_analyst_comment SET domain_id=1")
    
    op.alter_column('market_analyst_comment', 'domain_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('market_comment_domain_id_fkey', 'market_analyst_comment', type_='foreignkey')
    op.create_foreign_key('market_comment_domain_id_fkey', 'market_analyst_comment', 'domain', ['domain_id'], ['id'])
    
    # email_logs column
    op.add_column('email_logs', sa.Column('domain_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('email_logs_domain_id_fkey', 'email_logs', 'domain', ['domain_id'], ['id'])
    op.execute("UPDATE email_logs SET domain_id=1")

    op.alter_column('email_logs', 'domain_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('email_logs_domain_id_fkey', 'email_logs', type_='foreignkey')
    op.create_foreign_key('email_logs_domain_id_fkey', 'email_logs', 'domain', ['domain_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('market_comment_domain_id_fkey', 'market_analyst_comment', type_='foreignkey')
    op.drop_column('market_analyst_comment', 'domain_id')

    # email_log column drop
    op.drop_constraint('email_logs_domain_id_fkey', 'email_logs', type_='foreignkey')
    op.drop_column('email_logs', 'domain_id')
    # ### end Alembic commands ###
