"""empty message

Revision ID: 8bcac735eac5
Revises: cc65ddf292a8
Create Date: 2018-05-28 13:52:18.088062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcac735eac5'
down_revision = 'cc65ddf292a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_profile', sa.Column('market_cap', sa.BigInteger(), nullable=True))
    op.add_column('user_settings', sa.Column('allow_admin_access', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_settings SET allow_admin_access=false")
    op.alter_column('user_settings', 'allow_admin_access', nullable=False)
    op.add_column('user_settings', sa.Column('search_privacy_market_cap_max', sa.BigInteger(), nullable=True))
    op.add_column('user_settings', sa.Column('search_privacy_market_cap_min', sa.BigInteger(), nullable=True))
    op.drop_column('user_settings', 'search_privacy_market_cap')
    op.execute("UPDATE user_settings SET search_privacy_market_cap_max=9223372036854775807")
    op.execute("UPDATE user_settings SET search_privacy_market_cap_min=0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('search_privacy_market_cap', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user_settings', 'search_privacy_market_cap_min')
    op.drop_column('user_settings', 'search_privacy_market_cap_max')
    op.drop_column('user_settings', 'allow_admin_access')
    op.drop_column('account_profile', 'market_cap')
    # ### end Alembic commands ###
