"""empty message

Revision ID: 8cd977bc16c0
Revises: 9e0127b82f9f
Create Date: 2018-08-21 16:34:38.264008

"""
from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision = '8cd977bc16c0'
down_revision = '9e0127b82f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_invitee', sa.Column('status', app.base.model_fields.ChoiceString(app.webinar_resources.webinar_invitees.constants.WBNR_INV_STATUS_CHOICES)))
    op.execute("UPDATE webinar_invitee SET status='" + app.webinar_resources.webinar_invitees.constants.INVITED + "'" + " where conference_url IS NULL")
    op.execute("UPDATE webinar_invitee SET status='" + app.webinar_resources.webinar_invitees.constants.REGISTERED + "'" + " where conference_url IS NOT NULL")
    op.alter_column('webinar_invitee', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_invitee', 'status')
    # ### end Alembic commands ###
