"""empty message

Revision ID: 8d8850d34354
Revises: b8ed07b30b65
Create Date: 2019-01-16 13:46:33.886963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d8850d34354'
down_revision = 'b8ed07b30b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event', sa.Column('transcript_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event', 'transcript_filename')
    # ### end Alembic commands ###
