"""empty message

Revision ID: 93b2749e7239
Revises: fb20af7d37e4
Create Date: 2018-07-17 11:53:33.963552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b2749e7239'
down_revision = 'fb20af7d37e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar', sa.Column('conference_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar', 'conference_id')
    # ### end Alembic commands ###
