"""empty message

Revision ID: 93bee3837f7a
Revises: b7481117248e
Create Date: 2019-02-25 15:42:35.340397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bee3837f7a'
down_revision = 'b7481117248e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_key')
    # ### end Alembic commands ###
