"""empty message

Revision ID: 96c2a2c79582
Revises: e37d65f0cffb
Create Date: 2018-03-22 17:42:40.672117

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '96c2a2c79582'
down_revision = 'e37d65f0cffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast_host', sa.Column('host_designation', sa.String(length=128), nullable=True))
    op.add_column('webcast_host', sa.Column('host_email', app.base.model_fields.LCString(length=128), nullable=True))
    op.add_column('webcast_host', sa.Column('host_first_name', sa.String(length=128), nullable=True))
    op.add_column('webcast_host', sa.Column('host_last_name', sa.String(length=128), nullable=True))
    op.drop_constraint('c_webcast_id_host_id_key', 'webcast_host', type_='unique')
    op.add_column('webinar_host', sa.Column('host_designation', sa.String(length=128), nullable=True))
    op.add_column('webinar_host', sa.Column('host_email', app.base.model_fields.LCString(length=128), nullable=True))
    op.add_column('webinar_host', sa.Column('host_first_name', sa.String(length=128), nullable=True))
    op.add_column('webinar_host', sa.Column('host_last_name', sa.String(length=128), nullable=True))
    op.add_column('webinar_participant', sa.Column('participant_designation', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_participant', 'participant_designation')
    op.drop_column('webinar_host', 'host_last_name')
    op.drop_column('webinar_host', 'host_first_name')
    op.drop_column('webinar_host', 'host_email')
    op.drop_column('webinar_host', 'host_designation')
    op.create_unique_constraint('c_webcast_id_host_id_key', 'webcast_host', ['webcast_id', 'host_id'])
    op.drop_column('webcast_host', 'host_last_name')
    op.drop_column('webcast_host', 'host_first_name')
    op.drop_column('webcast_host', 'host_email')
    op.drop_column('webcast_host', 'host_designation')
    # ### end Alembic commands ###
