"""empty message

Revision ID: 97113148f8c7
Revises: e6a9b3360e9e
Create Date: 2018-01-09 13:28:37.899113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97113148f8c7'
down_revision = 'e6a9b3360e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_project_parameter', sa.Column('has_value', sa.Boolean(), nullable=True))
    op.add_column('ref_project_parameter', sa.Column('has_yes_no', sa.Boolean(), nullable=True))
    op.drop_constraint('webcast_host_fkey', 'webcast', type_='foreignkey')
    op.create_foreign_key('webcast_host_fkey', 'webcast', 'user', ['host_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('webcast_invitee_invitee_id_fkey', 'webcast_invitee', type_='foreignkey')
    op.create_foreign_key('webcast_invitee_invitee_id_fkey', 'webcast_invitee', 'user', ['invitee_id'], ['id'])
    op.drop_constraint('webinar_host_fkey', 'webinar', type_='foreignkey')
    op.create_foreign_key('webinar_host_fkey', 'webinar', 'user', ['host_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('webinar_chat_message_sent_to_fkey', 'webinar_chat_message', type_='foreignkey')
    op.drop_constraint('webinar_chat_message_in_reply_to_fkey', 'webinar_chat_message', type_='foreignkey')
    op.create_foreign_key('webinar_chat_message_sent_to_fkey', 'webinar_chat_message', 'user', ['sent_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('webinar_chat_message_in_reply_to_fkey', 'webinar_chat_message', 'webinar_chat_message', ['in_reply_to'], ['id'], ondelete='SET NULL')
    op.drop_constraint('webinar_invitee_invitee_id_fkey', 'webinar_invitee', type_='foreignkey')
    op.create_foreign_key('webinar_invitee_invitee_id_fkey', 'webinar_invitee', 'user', ['invitee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('webinar_invitee_invitee_id_fkey', 'webinar_invitee', type_='foreignkey')
    op.create_foreign_key('webinar_invitee_invitee_id_fkey', 'webinar_invitee', 'user', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('webinar_chat_message_in_reply_to_fkey', 'webinar_chat_message', type_='foreignkey')
    op.drop_constraint('webinar_chat_message_sent_to_fkey', 'webinar_chat_message', type_='foreignkey')
    op.create_foreign_key('webinar_chat_message_in_reply_to_fkey', 'webinar_chat_message', 'webinar_chat_message', ['in_reply_to'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('webinar_chat_message_sent_to_fkey', 'webinar_chat_message', 'user', ['sent_to'], ['id'], ondelete='CASCADE')
    op.drop_constraint('webinar_host_fkey', 'webinar', type_='foreignkey')
    op.create_foreign_key('webinar_host_fkey', 'webinar', 'user', ['host_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('webcast_invitee_invitee_id_fkey', 'webcast_invitee', type_='foreignkey')
    op.create_foreign_key('webcast_invitee_invitee_id_fkey', 'webcast_invitee', 'user', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('webcast_host_fkey', 'webcast', type_='foreignkey')
    op.create_foreign_key('webcast_host_fkey', 'webcast', 'user', ['host_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ref_project_parameter', 'has_yes_no')
    op.drop_column('ref_project_parameter', 'has_value')
    # ### end Alembic commands ###
