"""empty message

Revision ID: 97a5aa918537
Revises: 0c151dbf2c8c
Create Date: 2018-04-19 17:11:10.514532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97a5aa918537'
down_revision = '0c151dbf2c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event', 'agendas')
    op.add_column('corporate_access_event_stats', sa.Column('total_agendas', sa.BigInteger(), nullable=True))
    op.add_column('corporate_access_event_stats', sa.Column('total_non_slot_meetings', sa.BigInteger(), nullable=True))
    op.execute("UPDATE corporate_access_event_stats SET total_agendas=0")
    op.execute("UPDATE corporate_access_event_stats SET total_non_slot_meetings=0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event_stats', 'total_non_slot_meetings')
    op.drop_column('corporate_access_event_stats', 'total_agendas')
    op.add_column('corporate_access_event', sa.Column('agendas', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
