"""empty message

Revision ID: 9841959e00f8
Revises: 6a6b1884492f
Create Date: 2019-12-18 09:24:27.508695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9841959e00f8'
down_revision = '6a6b1884492f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('project', 'status_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'1'::bigint"))
    op.execute("update project set status_id=null;")
    op.execute(
        "SELECT setval('project_status_id_seq', (select max(id) from project_status), true);")
    op.add_column('project',
                  sa.Column('slides_completed', sa.Integer(),server_default='0', nullable=True))
    op.execute("insert into role (created_date, modified_date, name, permissions, created_by, updated_by, deleted) values(current_timestamp, current_timestamp, 'designer', '{""add user""}', 1, 1, '0')")
    op.execute("insert into role (created_date, modified_date, name, permissions, created_by, updated_by, deleted) values(current_timestamp, current_timestamp, 'analyst', '{""add user""}', 1, 1, '0')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update project set status_id=1;")
    op.alter_column('project', 'status_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.drop_column('project', 'slides_completed')
    # ### end Alembic commands ###
