"""empty message

Revision ID: 9afa366f669d
Revises: 1a87414aae2e
Create Date: 2021-11-24 18:40:04.152430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9afa366f669d'
down_revision = '1a87414aae2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_result_tracker',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('concall_date', sa.DateTime(), nullable=True),
    sa.Column('concall_bse_id', sa.BigInteger(), nullable=True),
    sa.Column('result_intimation_id', sa.BigInteger(), nullable=True),
    sa.Column('result_declaration_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='result_master_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concall_bse_id'], ['bse_corp_feed.id'], name='account_result_tracker_concall_bse_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_declaration_id'], ['bse_corp_feed.id'], name='account_result_tracker_result_declaration_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_intimation_id'], ['bse_corp_feed.id'], name='account_result_tracker_result_intimation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('result_master')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_master',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('result_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('result_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('concall_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('announcement_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='result_master_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['announcement_id'], ['bse_corp_feed.id'], name='result_master_bse_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='result_master_pkey')
    )
    op.drop_table('account_result_tracker')
    # ### end Alembic commands ###
