"""empty message

Revision ID: 9b8c5cda3a74
Revises: ef151c063f97
Create Date: 2020-01-01 16:02:55.614813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b8c5cda3a74'
down_revision = 'f2e88caf785b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('registration_request', sa.Column('only_design_lab', sa.Boolean(), server_default= '0', nullable=True))
    op.alter_column('registration_request', 'domain_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'1'::bigint"))
    op.add_column('user', sa.Column('only_design_lab', sa.Boolean(), server_default= '0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'only_design_lab')
    op.alter_column('registration_request', 'domain_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'1'::bigint"))
    op.drop_column('registration_request', 'only_design_lab')
    # ### end Alembic commands ###
