"""empty message

Revision ID: 9dbeb508c2e2
Revises: f7c2eb1ef2df
Create Date: 2019-08-28 11:38:44.377732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9dbeb508c2e2'
#down_revision = 'f7c2eb1ef2df'
down_revision = 'c7f9a7e01353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('admin_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('project_admin_id_fkey', 'project', 'user', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_admin_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'admin_id')
    # ### end Alembic commands ###
