"""empty message

Revision ID: 9e379e8f3bd1
Revises: 4e76452fb4af
Create Date: 2019-10-21 10:32:35.795033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e379e8f3bd1'
down_revision = '4e76452fb4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_request', sa.Column('domain_id', sa.BigInteger(), nullable=False, server_default='1'))
    op.create_foreign_key('registration_request_domain_id_fkey', 'registration_request', 'domain', ['domain_id'], ['id'], ondelete='RESTRICT')
    op.add_column('news_item',
                  sa.Column('domain_id', sa.BigInteger(), nullable=False,
                            server_default='1'))
    op.create_foreign_key('news_item_domain_id_fkey', 'news_item', 'domain',
                          ['domain_id'], ['id'], ondelete='RESTRICT')
    op.add_column('news_source',
                  sa.Column('domain_id', sa.BigInteger(), nullable=False,
                            server_default='1'))
    op.create_foreign_key('news_source_domain_id_fkey', 'news_source',
                          'domain', ['domain_id'], ['id'], ondelete='RESTRICT')
    op.add_column('twitter_feed',
                  sa.Column('domain_id', sa.BigInteger(), nullable=False,
                            server_default='1'))
    op.create_foreign_key('twitter_feed_domain_id_fkey', 'twitter_feed',
                          'domain', ['domain_id'], ['id'], ondelete='RESTRICT')
    op.add_column('twitter_source',
                  sa.Column('domain_id', sa.BigInteger(), nullable=False,
                            server_default='1'))
    op.create_foreign_key('twitter_source_domain_id_fkey', 'twitter_source',
                          'domain', ['domain_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registration_request_domain_id_fkey', 'registration_request', type_='foreignkey')
    op.drop_column('registration_request', 'domain_id')
    op.drop_constraint('twitter_source_domain_id_fkey', 'twitter_source',
                       type_='foreignkey')
    op.drop_column('twitter_source', 'domain_id')
    op.drop_constraint('twitter_feed_domain_id_fkey', 'twitter_feed',
                       type_='foreignkey')
    op.drop_column('twitter_feed', 'domain_id')
    op.drop_constraint('news_source_domain_id_fkey', 'news_source',
                       type_='foreignkey')
    op.drop_column('news_source', 'domain_id')
    op.drop_constraint('news_item_domain_id_fkey', 'news_item',
                       type_='foreignkey')
    op.drop_column('news_item', 'domain_id')
    # ### end Alembic commands ###
