"""empty message

Revision ID: a5c6569c00fc
Revises: 72f2cad79a50
Create Date: 2019-01-24 12:32:39.928409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c6569c00fc'
down_revision = '72f2cad79a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_collaborator', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute("UPDATE corporate_access_event_collaborator SET is_mail_sent=True")
    op.add_column('corporate_access_event_host', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute(
        "UPDATE corporate_access_event_host SET is_mail_sent=True")
    op.add_column('corporate_access_event_invitee', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute(
        "UPDATE corporate_access_event_invitee SET is_mail_sent=True")
    op.add_column('corporate_access_event_participant', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute(
        "UPDATE corporate_access_event_participant SET is_mail_sent=True")
    op.add_column('corporate_access_event_rsvp', sa.Column('is_mail_sent', sa.Boolean(), nullable=True))
    op.execute(
        "UPDATE corporate_access_event_rsvp SET is_mail_sent=True")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event_rsvp', 'is_mail_sent')
    op.drop_column('corporate_access_event_participant', 'is_mail_sent')
    op.drop_column('corporate_access_event_invitee', 'is_mail_sent')
    op.drop_column('corporate_access_event_host', 'is_mail_sent')
    op.drop_column('corporate_access_event_collaborator', 'is_mail_sent')
    # ### end Alembic commands ###
