"""empty message

Revision ID: a7e4e9d48670
Revises: 3a7286aedb7b
Create Date: 2018-06-07 18:02:58.537069

"""
from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision = 'a7e4e9d48670'
down_revision = '3a7286aedb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'search_privacy_designation_level',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(app.base.model_fields.ChoiceString(app.resources.designations.constants.DES_LEVEL_TYPES_CHOICES)),
               existing_nullable=True,
               postgresql_using='search_privacy_designation_level::character varying[]')
    # set the default values
    def_levels = ','.join(('"' + level + '"') if ' ' in level else level for level in app.resources.designations.constants.DES_LEVEL_TYPES)
    op.execute("UPDATE user_settings SET search_privacy_designation_level='{" + def_levels + "}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'search_privacy_designation_level',
               existing_type=sa.ARRAY(app.base.model_fields.ChoiceString(app.resources.designations.constants.DES_LEVEL_TYPES_CHOICES)),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
