"""empty message

Revision ID: a8133d42df2c
Revises: c530308c7f7b
Create Date: 2018-07-19 16:17:52.151324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8133d42df2c'
down_revision = 'c530308c7f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar', sa.Column('admin_url', sa.String(length=256), nullable=True))
    op.add_column('webinar_invitee', sa.Column('conference_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_invitee', 'conference_url')
    op.drop_column('webinar', 'admin_url')
    # ### end Alembic commands ###
