"""empty message

Revision ID: a86ef8e7c97e
Revises: 01b160dc767d
Create Date: 2018-08-09 15:06:26.741833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a86ef8e7c97e'
down_revision = '01b160dc767d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_profile', 'sector_name')
    op.drop_column('account_profile', 'industry_name')
    op.drop_column('user_profile', 'sector_names')
    op.drop_column('user_profile', 'industry_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('industry_names', postgresql.ARRAY(sa.VARCHAR(length=256)), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('sector_names', postgresql.ARRAY(sa.VARCHAR(length=256)), autoincrement=False, nullable=True))
    op.add_column('account_profile', sa.Column('industry_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('account_profile', sa.Column('sector_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
