"""empty message

Revision ID: ab13c1b3ee5b
Revises: 29a343154f6c
Create Date: 2018-07-03 12:03:10.439617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab13c1b3ee5b'
down_revision = '29a343154f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast_invitee', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('webcast_invitee_user_id_fkey', 'webcast_invitee', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('webcast_invitee_user_id_fkey', 'webcast_invitee', type_='foreignkey')
    op.drop_column('webcast_invitee', 'user_id')
    # ### end Alembic commands ###
