"""empty message

Revision ID: abd58cf2da48
Revises: a7e4e9d48670
Create Date: 2018-06-12 18:27:43.242267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd58cf2da48'
down_revision = 'a7e4e9d48670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_participant', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('c_corp_corporate_access_event_id_sequence_id_key', 'corporate_access_event_participant', ['corporate_access_event_id', 'sequence_id'])
    op.add_column('corporate_access_event_rsvp', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('c_corprsvp_corporate_access_event_id_sequence_id_key', 'corporate_access_event_rsvp', ['corporate_access_event_id', 'sequence_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('c_corprsvp_corporate_access_event_id_sequence_id_key', 'corporate_access_event_rsvp', type_='unique')
    op.drop_column('corporate_access_event_rsvp', 'sequence_id')
    op.drop_constraint('c_corp_corporate_access_event_id_sequence_id_key', 'corporate_access_event_participant', type_='unique')
    op.drop_column('corporate_access_event_participant', 'sequence_id')
    # ### end Alembic commands ###
