"""empty message

Revision ID: ac2a409a8d0c
Revises: 59d3dc7dcb84
Create Date: 2019-05-28 19:05:06.446391

"""
from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql
from app.resources.accounts.constants import ACCT_TYPES_CHOICES

# revision identifiers, used by Alembic.
revision = 'ac2a409a8d0c'
# down_revision = 'ad2de29b2eb6'
down_revision = 'd5b90fe3f1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column(
        'account_type', app.base.model_fields.ChoiceString(
                ACCT_TYPES_CHOICES, nullable=True)))
    op.add_column('role', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('description', sa.String(length=256),
                                    nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'sequence')
    op.drop_column('role', 'is_active')
    op.drop_column('role', 'account_type')
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
