"""empty message

Revision ID: ac58c4ecbabc
Revises: 8bcac735eac5
Create Date: 2018-05-30 13:35:14.853931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac58c4ecbabc'
down_revision = '8bcac735eac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_notification_count', sa.BigInteger(), nullable=True))
    op.execute("UPDATE public.user SET current_notification_count=0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_notification_count')
    # ### end Alembic commands ###
