"""empty message

Revision ID: ad2de29b2eb6
Revises: 0ca22e8b818b
Create Date: 2019-05-20 16:27:40.195768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad2de29b2eb6'
down_revision = '0ca22e8b818b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_distribution_invitee_list', sa.Column('sent_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_distribution_invitee_list', 'sent_on')
    # ### end Alembic commands ###
