"""empty message

Revision ID: ad732cfdad89
Revises: 89fb41b3a7b9
Create Date: 2018-10-30 12:57:40.449758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad732cfdad89'
down_revision = '302ac347ebd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_request', sa.Column('by_admin', sa.Boolean(), nullable=True))
    op.execute('update registration_request set by_admin=False')
    op.add_column('user', sa.Column('is_registration_request', sa.Boolean(), nullable=True))
    op.execute('update "user" set is_registration_request=False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_registration_request')
    op.drop_column('registration_request', 'by_admin')
    # ### end Alembic commands ###
