"""empty message

Revision ID: afa69900f827
Revises: 02ec2dc6859b
Create Date: 2021-11-02 13:48:44.306435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa69900f827'
down_revision = 'dbe0f7671bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_tracker_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('is_favourite', sa.Boolean(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='result_tracker_user_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_tracker_group_companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='result_tracker_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['result_tracker_group.id'], name='result_tracker_user_company_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column('corporate_announcement', sa.Column('conall_date', sa.DateTime(), nullable=True))
    # op.drop_column('crm_contact', 'industry')
    # op.alter_column('personalised_video_invitee', 'account_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.create_foreign_key(None, 'personalised_video_invitee', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'personalised_video_invitee', type_='foreignkey')
    # op.alter_column('personalised_video_invitee', 'account_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.add_column('crm_contact', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('corporate_announcement', 'conall_date')
    op.drop_table('result_tracker_group_companies')
    op.drop_table('result_tracker_group')
    # ### end Alembic commands ###
