"""empty message

Revision ID: b04186209f25
Revises: 8cd977bc16c0
Create Date: 2018-08-23 16:45:14.398584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04186209f25'
down_revision = '8cd977bc16c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_logout', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('unsuccessful_login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unsuccessful_login_count')
    op.drop_column('user', 'last_logout')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
