"""empty message

Revision ID: b0641c131cbe
Revises: 4ccb04ef3b7c
Create Date: 2018-11-29 18:05:12.464042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0641c131cbe'
down_revision = '4ccb04ef3b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_contact', sa.Column('is_system_user', sa.Boolean(), nullable=True))
    op.execute("UPDATE crm_contact SET is_system_user=false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_contact', 'is_system_user')

    # ### end Alembic commands ###
