"""empty message

Revision ID: b25cf7727f79
Revises: c30ac9fc6dff
Create Date: 2022-01-05 19:18:07.577371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b25cf7727f79'
down_revision = '17abd73e8f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('c_announcement_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('notification_c_announcement_id_fkey', 'notification', 'corporate_announcement', ['c_announcement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_c_announcement_id_fkey', 'notification', type_='foreignkey')
    op.drop_column('notification', 'c_announcement_id')
    # ### end Alembic commands ###
