"""empty message

Revision ID: b33460baff13
Revises: 6181c88ad5b3
Create Date: 2021-11-23 13:23:40.664875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33460baff13'
down_revision = '6181c88ad5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_master',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('result_date', sa.DateTime(), nullable=True),
    sa.Column('result_url', sa.String(length=256), nullable=True),
    sa.Column('concall_date', sa.DateTime(), nullable=True),
    sa.Column('announcement_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='result_master_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['announcement_id'], ['bse_corp_feed.id'], name='result_master_bse_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('result_tracker_group_companies', sa.Column('result_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('result_master_fkey', 'result_tracker_group_companies', 'result_master', ['result_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_master_fkey', 'result_tracker_group_companies', type_='foreignkey')
    op.drop_column('result_tracker_group_companies', 'result_id')
    op.drop_table('result_master')
    # ### end Alembic commands ###
