"""empty message

Revision ID: b3c35fd22d8d
Revises: 1e88b88fe46a
Create Date: 2018-12-20 11:18:16.406836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision = 'b3c35fd22d8d'
down_revision = '1e88b88fe46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_attendee', sa.Column('attendee_email', app.base.model_fields.LCString(length=128), nullable=True))
    op.add_column('webinar_attendee', sa.Column('attendee_first_name', sa.String(length=128), nullable=True))
    op.add_column('webinar_attendee', sa.Column('attendee_last_name', sa.String(length=128), nullable=True))
    op.alter_column('webinar_attendee', 'attendee_id', existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webinar_attendee', 'attendee_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('webinar_attendee', 'attendee_last_name')
    op.drop_column('webinar_attendee', 'attendee_first_name')
    op.drop_column('webinar_attendee', 'attendee_email')
    # ### end Alembic commands ###
