"""empty message

Revision ID: b531b0e89736
Revises: a5c6569c00fc
Create Date: 2019-01-28 13:29:35.542080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b531b0e89736'
down_revision = 'a5c6569c00fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_announcement', sa.Column('ca_event_audio_file_id', sa.BigInteger(), nullable=True))
    op.add_column('corporate_announcement', sa.Column('ca_event_transcript_file_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('announcement_ca_event_transcript_file_id_fkey', 'corporate_announcement', 'corporate_access_event', ['ca_event_transcript_file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('announcement_ca_event_audio_file_id_fkey', 'corporate_announcement', 'corporate_access_event', ['ca_event_audio_file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('announcement_ca_event_audio_file_id_fkey', 'corporate_announcement', type_='foreignkey')
    op.drop_constraint('announcement_ca_event_transcript_file_id_fkey', 'corporate_announcement', type_='foreignkey')
    op.drop_column('corporate_announcement', 'ca_event_transcript_file_id')
    op.drop_column('corporate_announcement', 'ca_event_audio_file_id')
    # ### end Alembic commands ###
