"""empty message

Revision ID: b64ae57275f5
Revises: 9e6cb1f5b288
Create Date: 2018-03-14 20:30:58.582009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64ae57275f5'
down_revision = '9e6cb1f5b288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_ref_event_sub_type', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('corporate_access_ref_event_type', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_ref_event_type', 'deleted')
    op.drop_column('corporate_access_ref_event_sub_type', 'deleted')
    # ### end Alembic commands ###
