"""empty message

Revision ID: b7481117248e
Revises: afb862103eb1
Create Date: 2019-02-22 15:32:27.627453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7481117248e'
down_revision = 'afb862103eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_item', sa.Column('news_name', sa.String(length=512), nullable=False))
    op.add_column('news_item', sa.Column('news_url', sa.String(length=1024), nullable=False))
    op.add_column('news_item_archive', sa.Column('news_name', sa.String(length=512), nullable=False))
    op.add_column('news_item_archive', sa.Column('news_url', sa.String(length=1024), nullable=False))
    op.alter_column('news_item_archive', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_item_archive', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_column('news_item_archive', 'news_url')
    op.drop_column('news_item_archive', 'news_name')
    op.drop_column('news_item', 'news_url')
    op.drop_column('news_item', 'news_name')
    # ### end Alembic commands ###
