"""empty message

Revision ID: b8db6a201d83
Revises: 9afa366f669d
Create Date: 2021-11-25 10:47:33.627606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8db6a201d83'
down_revision = '1be4ea4aba54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('result_tracker_account_id_key', 'account_result_tracker', ['account_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_tracker_account_id_key', 'account_result_tracker', type_='unique')
    # ### end Alembic commands ###
