"""empty message

Revision ID: b8ed07b30b65
Revises: 277f96bada1c
Create Date: 2019-01-07 11:45:38.257396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ed07b30b65'
down_revision = '277f96bada1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('request_device_ids', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('notification',
                  sa.Column('admin_publish_notification_id', sa.BigInteger(),
                            nullable=True))
    op.create_foreign_key('notification_admin_publish_notification_id_fkey',
                          'notification', 'admin_publish_notification',
                          ['admin_publish_notification_id'], ['id'],
                          ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_admin_publish_notification_id_fkey',
                       'notification', type_='foreignkey')
    op.drop_column('notification', 'admin_publish_notification_id')
    op.drop_column('user_settings', 'request_device_ids')
    # ### end Alembic commands ###
