"""empty message

Revision ID: bc075dc6fe44
Revises: 8721d0a85680
Create Date: 2019-09-26 14:42:36.214516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc075dc6fe44'
down_revision = '8721d0a85680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchreportannouncements',
    sa.Column('research_report_id', sa.BigInteger(), nullable=False),
    sa.Column('announcement_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['corporate_announcement.id'], name='resreportannouns_announces_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_report_id'], ['research_report.id'], name='resreportannouns_research_report_id_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('research_report_id', 'announcement_id', name='ra_research_report_id_announcement_id_key')
    )
    op.add_column('research_report', sa.Column('thumbnail_name', sa.String(), nullable=True))
    op.add_column('research_report',
                  sa.Column('chart_end_date', sa.String(length=32),
                            nullable=True))
    op.add_column('research_report',
                  sa.Column('chart_start_date', sa.String(length=32),
                            nullable=True))
    op.add_column('research_report',
                  sa.Column('key_stat', sa.Boolean(), nullable=True))
    op.add_column('research_report',
                  sa.Column('stock_chart', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_report', 'thumbnail_name')
    op.alter_column('news_item', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_table('researchreportannouncements')
    op.drop_column('research_report', 'stock_chart')
    op.drop_column('research_report', 'key_stat')
    op.drop_column('research_report', 'chart_start_date')
    op.drop_column('research_report', 'chart_end_date')
    # ### end Alembic commands ###
