"""empty message

Revision ID: bc77f43154f1
Revises: 28926377d629
Create Date: 2020-10-05 15:30:21.676675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc77f43154f1'
down_revision = '28926377d629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    reminder_types = postgresql.ENUM('notification','email',name='reminder_types')
    reminder_types.create(op.get_bind())

    op.add_column('activity', sa.Column('reminder_type', sa.Enum('notification', 'email', name='reminder_types'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('activity', 'reminder_type')

    reminder_types = postgresql.ENUM('notification','email',name='reminder_type')
    reminder_types.drop(op.get_bind())
    # ### end Alembic commands ###
