"""empty message

Revision ID: bcf277b594a5
Revises: 97dbdb1fcecf
Create Date: 2019-11-15 13:15:53.633296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcf277b594a5'
# down_revision = '97dbdb1fcecf'
down_revision = 'f7c2eb1ef2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcast', sa.Column('recording_published', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('webinar', sa.Column('recording_published', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar', 'recording_published')
    op.drop_column('webcast', 'recording_published')

    # ### end Alembic commands ###
