"""empty message

Revision ID: bdd4a7b62079
Revises: 1e91172e3671
Create Date: 2019-10-16 07:11:35.535222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdd4a7b62079'
down_revision = '653ab361dc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('blocked', sa.Boolean(), nullable=True,
                                       server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'blocked')
    # ### end Alembic commands ###
