"""empty message

Revision ID: bfc64779f03b
Revises: 4a05cb9bd1f9
Create Date: 2018-07-27 20:38:59.600470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app

# revision identifiers, used by Alembic.
revision = 'bfc64779f03b'
down_revision = '4a05cb9bd1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notification_ca_open_meeting_inquiry_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_ca_open_meeting_slot_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key('notification_ca_open_meeting_slot_id_fkey', 'notification', 'ca_open_meeting_slot', ['ca_open_meeting_slot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('notification_ca_open_meeting_inquiry_id_fkey', 'notification', 'ca_open_meeting_inquiry', ['ca_open_meeting_inquiry_id'], ['id'], ondelete='SET NULL')
    op.add_column('webinar_attendee', sa.Column('browser_name', sa.String(length=128), nullable=True))
    op.add_column('webinar_attendee', sa.Column('browser_version', sa.String(length=128), nullable=True))
    op.add_column('webinar_attendee', sa.Column('chats_count', sa.BigInteger(), nullable=True))
    op.add_column('webinar_attendee', sa.Column('device_name', sa.String(length=128), nullable=True))
    op.add_column('webinar_attendee', sa.Column('engaged_duration', sa.String(length=16), nullable=True))
    op.add_column('webinar_attendee', sa.Column('entered_at', sa.DateTime(), nullable=True))
    op.add_column('webinar_attendee', sa.Column('handouts', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('webinar_attendee', sa.Column('leaved_at', sa.DateTime(), nullable=True))
    op.add_column('webinar_attendee', sa.Column('polls', app.base.model_fields.CastingArray(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    op.add_column('webinar_attendee', sa.Column('polls_count', sa.BigInteger(), nullable=True))
    op.add_column('webinar_attendee', sa.Column('qas_count', sa.BigInteger(), nullable=True))
    op.add_column('webinar_attendee', sa.Column('questions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('webinar_attendee', sa.Column('total_duration', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_attendee', 'total_duration')
    op.drop_column('webinar_attendee', 'questions')
    op.drop_column('webinar_attendee', 'qas_count')
    op.drop_column('webinar_attendee', 'polls_count')
    op.drop_column('webinar_attendee', 'polls')
    op.drop_column('webinar_attendee', 'leaved_at')
    op.drop_column('webinar_attendee', 'handouts')
    op.drop_column('webinar_attendee', 'entered_at')
    op.drop_column('webinar_attendee', 'engaged_duration')
    op.drop_column('webinar_attendee', 'device_name')
    op.drop_column('webinar_attendee', 'chats_count')
    op.drop_column('webinar_attendee', 'browser_version')
    op.drop_column('webinar_attendee', 'browser_name')
    op.drop_constraint('notification_ca_open_meeting_inquiry_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_ca_open_meeting_slot_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key('notification_ca_open_meeting_slot_id_fkey', 'notification', 'ca_open_meeting_slot', ['ca_open_meeting_slot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('notification_ca_open_meeting_inquiry_id_fkey', 'notification', 'ca_open_meeting_inquiry', ['ca_open_meeting_inquiry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
