"""empty message

Revision ID: c29c8a7cba48
Revises: d8a02f538bf8
Create Date: 2018-09-05 15:59:00.705094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29c8a7cba48'
down_revision = 'd8a02f538bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('export_enabled', sa.Boolean(), nullable=True))
    op.execute("UPDATE account SET export_enabled=false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'export_enabled')
    # ### end Alembic commands ###
