"""empty message

Revision ID: c3e04c6efa6a
Revises: 0150987c09ed
Create Date: 2021-11-03 17:06:49.580379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e04c6efa6a'
down_revision = 'afa69900f827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_announcement', sa.Column('conall_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint('result_tracker_user_id_group_name_uniquekey', 'result_tracker_group', ['user_id', 'group_name'])
    op.create_unique_constraint('result_tracker_group_id_account_id_uniquekey', 'result_tracker_group_companies', ['group_id', 'account_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('result_tracker_group_id_account_id_uniquekey', 'result_tracker_group_companies', type_='unique')
    op.drop_constraint('result_tracker_user_id_group_name_uniquekey', 'result_tracker_group', type_='unique')
    op.drop_column('corporate_announcement', 'conall_date')
    # ### end Alembic commands ###
