"""empty message

Revision ID: c530308c7f7b
Revises: 93b2749e7239
Create Date: 2018-07-17 20:22:06.956263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c530308c7f7b'
down_revision = '93b2749e7239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_open_meeting', sa.Column('cancelled', sa.Boolean(), nullable=True))
    op.alter_column('ca_open_meeting_invitee', 'invitee_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ca_open_meeting_invitee', 'invitee_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('ca_open_meeting', 'cancelled')
    # ### end Alembic commands ###
