"""empty message

Revision ID: c53a4b249820
Revises: c29c8a7cba48
Create Date: 2018-09-07 10:27:20.047671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53a4b249820'
down_revision = 'c29c8a7cba48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('management_profile', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE management_profile SET sequence_id=id")
    op.alter_column('management_profile', 'sequence_id', nullable=False)
    op.create_unique_constraint('c_acc_profile_id_sequence_id_key', 'management_profile', ['account_profile_id', 'sequence_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('c_acc_profile_id_sequence_id_key', 'management_profile', type_='unique')
    op.drop_column('management_profile', 'sequence_id')
    # ### end Alembic commands ###
