"""empty message

Revision ID: c7f9a7e01353
Revises: ac2a409a8d0c
Create Date: 2019-07-30 15:55:47.690274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7f9a7e01353'
down_revision = '22eecd95626e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('deleted', sa.Boolean(), server_default='0' ,nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'deleted')

    # ### end Alembic commands ###
