"""empty message

Revision ID: cb1f50b28c5c
Revises: 1623fb76bf51
Create Date: 2018-04-05 18:17:25.392383

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'cb1f50b28c5c'
down_revision = '1623fb76bf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event', sa.Column('agendas', app.base.model_fields.CastingArray(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event', 'agendas')
    # ### end Alembic commands ###
