"""empty message

Revision ID: cbd26a0de3b3
Revises: 2be8d7abb34a
Create Date: 2018-03-22 18:58:55.106990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd26a0de3b3'
down_revision = '2be8d7abb34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporate_access_event_host', 'host_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint('c_corporate_access_event_id_host_email_key', 'corporate_access_event_host', ['corporate_access_event_id', 'host_email'])
    op.create_unique_constraint('c_created_by_corpacc_event_id_invitee_email_key', 'corporate_access_event_invitee', ['created_by', 'corporate_access_event_id', 'invitee_email'])
    op.create_unique_constraint('c_created_by_corpacc_event_id_invitee_id_key', 'corporate_access_event_invitee', ['created_by', 'corporate_access_event_id', 'invitee_id'])
    op.drop_constraint('c_created_by_corpacc_event_id_invitee_id_invitee_email_key', 'corporate_access_event_invitee', type_='unique')
    op.create_unique_constraint('c_corp_access_evt_id_participant_email_key', 'corporate_access_event_participant', ['corporate_access_event_id', 'participant_email'])
    op.create_unique_constraint('c_corp_access_evt_id_participant_id_key', 'corporate_access_event_participant', ['corporate_access_event_id', 'participant_id'])
    op.drop_constraint('c_corp_access_evt_id_participant_id_participant_email_key', 'corporate_access_event_participant', type_='unique')
    op.alter_column('webcast_host', 'host_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('webinar_host', 'host_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webinar_host', 'host_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('webcast_host', 'host_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint('c_corp_access_evt_id_participant_id_participant_email_key', 'corporate_access_event_participant', ['corporate_access_event_id', 'participant_id', 'participant_email'])
    op.drop_constraint('c_corp_access_evt_id_participant_id_key', 'corporate_access_event_participant', type_='unique')
    op.drop_constraint('c_corp_access_evt_id_participant_email_key', 'corporate_access_event_participant', type_='unique')
    op.create_unique_constraint('c_created_by_corpacc_event_id_invitee_id_invitee_email_key', 'corporate_access_event_invitee', ['created_by', 'corporate_access_event_id', 'invitee_id', 'invitee_email'])
    op.drop_constraint('c_created_by_corpacc_event_id_invitee_id_key', 'corporate_access_event_invitee', type_='unique')
    op.drop_constraint('c_created_by_corpacc_event_id_invitee_email_key', 'corporate_access_event_invitee', type_='unique')
    op.drop_constraint('c_corporate_access_event_id_host_email_key', 'corporate_access_event_host', type_='unique')
    op.alter_column('corporate_access_event_host', 'host_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
