"""empty message

Revision ID: cc65ddf292a8
Revises: 6b7a9a71eff9
Create Date: 2018-05-21 14:49:30.534892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc65ddf292a8'
down_revision = '6b7a9a71eff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_ref_event_sub_type', sa.Column('show_time', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_ref_event_sub_type', 'show_time')
    # ### end Alembic commands ###
