"""empty message

Revision ID: cca507cc072b
Revises: 35d8058531e6
Create Date: 2018-07-12 19:23:44.350884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca507cc072b'
down_revision = '35d8058531e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_download_report', sa.Boolean(), nullable=True))
    op.execute("UPDATE public.account SET is_download_report=false")
    op.add_column('ca_open_meeting_slot', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('corporate_access_event_agenda', sa.Column('secondary_title', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event_slot', sa.Column('description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event_slot', 'description')
    op.drop_column('corporate_access_event_agenda', 'secondary_title')
    op.drop_column('ca_open_meeting_slot', 'description')
    op.drop_column('account', 'is_download_report')
    # ### end Alembic commands ###
