"""empty message

Revision ID: cd02c97a1a8e
Revises: 2aba3e13bb04
Create Date: 2018-09-18 11:15:47.736828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd02c97a1a8e'
down_revision = '2aba3e13bb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sequence_id', sa.Integer(), nullable=True))
    op.execute(
        'UPDATE "user" SET sequence_id=id')
    op.alter_column('user', 'sequence_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sequence_id')
    # ### end Alembic commands ###
