"""empty message

Revision ID: ce1957af2db4
Revises: db02e8673612
Create Date: 2018-07-10 19:47:42.017701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1957af2db4'
down_revision = 'db02e8673612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ca_open_meeting', sa.Column('description', sa.String(length=9216), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ca_open_meeting', 'description')
    # ### end Alembic commands ###
