"""empty message

Revision ID: d5b90fe3f1c9
Revises: 97dbdb1fcecf
Create Date: 2019-12-04 13:44:00.686602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5b90fe3f1c9'
# down_revision = '67bdae182cad'
down_revision = '97dbdb1fcecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_invitee', sa.Column('invitee_company', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event_invitee', 'invitee_company')
    # ### end Alembic commands ###
