"""empty message

Revision ID: d7771cfb467e
Revises: ac2a409a8d0c
Create Date: 2019-07-11 12:07:14.330537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7771cfb467e'
# down_revision = 'c7f9a7e01353'
down_revision = 'ac2a409a8d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    #op.add_column('permission', sa.Column('code', sa.String(length=32), nullable=True))
    op.execute('update permission set code = name;')
    #op.create_unique_constraint(None, 'permission', ['code'])
    # op.alter_column(
    #     table_name='permission',
    #     column_name='code',
    #     nullable=False
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    op.drop_column('permission', 'code')

    # ### end Alembic commands ###
