"""empty message

Revision ID: d8293404401e
Revises: 8535b1dca515
Create Date: 2018-03-20 15:24:47.922140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8293404401e'
down_revision = '8535b1dca515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_request', sa.Column('password', sa.String(length=128)))
    op.execute("UPDATE registration_request SET password='$$$$$$$$$$$$$'")
    op.alter_column('registration_request', 'password', nullable=False)
    op.add_column('user', sa.Column('unverified', sa.Boolean(), nullable=True))
    op.execute("UPDATE public.user SET unverified=false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unverified')
    op.drop_column('registration_request', 'password')
    # ### end Alembic commands ###
