"""empty message

Revision ID: d8a02f538bf8
Revises: 9e0127b82f9f
Create Date: 2018-08-18 14:30:15.214887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a02f538bf8'
down_revision = 'b04186209f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_parent', sa.Boolean(), nullable=True))
    op.add_column('account', sa.Column('parent_account_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('account_parent_account_id_fkey', 'account', 'account', ['parent_account_id'], ['id'], ondelete='CASCADE')
    op.execute("UPDATE account SET is_parent=false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_parent_account_id_fkey', 'account', type_='foreignkey')
    op.drop_column('account', 'parent_account_id')
    op.drop_column('account', 'is_parent')
    # ### end Alembic commands ###
