"""empty message

Revision ID: d8c5f83101b6
Revises: 2644b9c196cb
Create Date: 2018-04-02 11:37:54.308951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c5f83101b6'
down_revision = '2644b9c196cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_attendee', sa.Column('created_by', sa.BigInteger()))
    op.add_column('corporate_access_event_attendee', sa.Column('updated_by', sa.BigInteger()))
    op.execute("UPDATE corporate_access_event_attendee SET created_by=1")
    op.execute("UPDATE corporate_access_event_attendee SET updated_by=1")
    op.alter_column('corporate_access_event_attendee', 'created_by', nullable=False)
    op.alter_column('corporate_access_event_attendee', 'updated_by', nullable=False)
    op.create_foreign_key('corporate_access_event_attendee_updated_by_fkey', 'corporate_access_event_attendee', 'user', ['updated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('corporate_access_event_attendee_created_by_fkey', 'corporate_access_event_attendee', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('corporate_access_event_attendee_created_by_fkey', 'corporate_access_event_attendee', type_='foreignkey')
    op.drop_constraint('corporate_access_event_attendee_updated_by_fkey', 'corporate_access_event_attendee', type_='foreignkey')
    op.drop_column('corporate_access_event_attendee', 'updated_by')
    op.drop_column('corporate_access_event_attendee', 'created_by')
    # ### end Alembic commands ###
