"""empty message

Revision ID: da1cb0e9224c
Revises: bcf277b594a5
Create Date: 2019-11-18 07:01:43.291974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da1cb0e9224c'
down_revision = 'bcf277b594a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('designation', sa.Column('sequence', sa.Integer(), nullable=True))
    op.execute("update designation set sequence = 1 where designation_level = 'bod & top management';")
    op.execute(
        "update designation set sequence = 2 where designation_level = 'mid-level management';")
    op.execute(
        "update designation set sequence = 3 where designation_level = 'managers & others';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('designation', 'sequence')
    # ### end Alembic commands ###
