"""empty message

Revision ID: da652b46fa49
Revises: 57f3b3e6dc37
Create Date: 2021-01-22 16:28:27.349007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da652b46fa49'
down_revision = '57f3b3e6dc37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """op.add_column('crm_contact', sa.Column('about', sa.String(), nullable=True))
    op.add_column('fundmanagement', sa.Column('entity_proper_name', sa.String(), nullable=False))
    op.add_column('fundmanagement', sa.Column('factset_fund_id', sa.String(), nullable=True))
    op.drop_column('fundmanagement', 'is_profile')
    op.drop_column('fundmanagement', 'fund')"""
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundmanagement', sa.Column('fund', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('fundmanagement', sa.Column('is_profile', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('fundmanagement', 'factset_fund_id')
    op.drop_column('fundmanagement', 'entity_proper_name')
    op.drop_column('crm_contact', 'about')
    # ### end Alembic commands ###
