"""empty message

Revision ID: decfa5e5fbb0
Revises: 26c6a23bf268
Create Date: 2021-11-26 19:05:53.891032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'decfa5e5fbb0'
down_revision = 'b8db6a201d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_transcribe', sa.Column('transcript_job_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_transcribe', 'transcript_job_name')
    # ### end Alembic commands ###
