"""empty message

Revision ID: e37d65f0cffb
Revises: 6770adb786ae
Create Date: 2018-03-22 12:37:39.338764

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = 'e37d65f0cffb'
down_revision = '6770adb786ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_host', sa.Column('host_designation', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event_host', sa.Column('host_email', app.base.model_fields.LCString(length=128), nullable=True))
    op.add_column('corporate_access_event_host', sa.Column('host_first_name', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event_host', sa.Column('host_last_name', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event_invitee', sa.Column('invitee_designation', sa.String(length=128), nullable=True))
    op.add_column('corporate_access_event_participant', sa.Column('participant_designation', sa.String(length=128), nullable=True))
    op.add_column('webcast_invitee', sa.Column('invitee_designation', sa.String(length=128), nullable=True))
    op.add_column('webinar_invitee', sa.Column('invitee_designation', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_invitee', 'invitee_designation')
    op.drop_column('webcast_invitee', 'invitee_designation')
    op.drop_column('corporate_access_event_participant', 'participant_designation')
    op.drop_column('corporate_access_event_invitee', 'invitee_designation')
    op.drop_column('corporate_access_event_host', 'host_last_name')
    op.drop_column('corporate_access_event_host', 'host_first_name')
    op.drop_column('corporate_access_event_host', 'host_email')
    op.drop_column('corporate_access_event_host', 'host_designation')
    # ### end Alembic commands ###
