"""empty message

Revision ID: e776b8f37a1d
Revises: 1fe1b852fbf8
Create Date: 2021-08-25 15:47:20.967749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e776b8f37a1d'
down_revision = 'dde2cf4c07d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporate_announcement', 'announcement_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
     # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corporate_announcement', 'announcement_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
