"""empty message

Revision ID: e89b189441d4
Revises: da652b46fa49
Create Date: 2021-07-20 13:33:52.872781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89b189441d4'
down_revision = 'da652b46fa49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('crm_contact', 'industry')
    # op.add_column('project', sa.Column('esg_standard_id', sa.Integer(), nullable=True))
    #op.add_column('project', sa.Column('presentation_format_id', sa.Integer(), nullable=True))
    #op.create_foreign_key('project_project_sub_type_presentation_format_id_fkey', 'project', 'ref_project_sub_child_type', ['presentation_format_id'], ['id'])
    #op.create_foreign_key('project_project_sub_type_esg_standard_id_fkey', 'project', 'ref_project_sub_child_type', ['esg_standard_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_project_sub_type_esg_standard_id_fkey', 'project', type_='foreignkey')
    op.drop_constraint('project_project_sub_type_presentation_format_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'presentation_format_id')
    op.drop_column('project', 'esg_standard_id')
    op.add_column('crm_contact', sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###