"""empty message

Revision ID: eb7c33f1b04e
Revises: f4a3ce445102
Create Date: 2018-04-03 10:27:49.329170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7c33f1b04e'
down_revision = 'f4a3ce445102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event_attendee', sa.Column('comment', sa.String(length=256), nullable=True))
    op.drop_column('corporate_access_event_inquiry', 'comment')
    op.create_foreign_key('corporate_access_event_inquiry_his_created_by_fkey', 'corporate_access_event_inquiry_history', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('corporate_access_event_inquiry_his_created_by_fkey', 'corporate_access_event_inquiry_history', type_='foreignkey')
    op.add_column('corporate_access_event_inquiry', sa.Column('comment', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('corporate_access_event_attendee', 'comment')
    # ### end Alembic commands ###
