"""empty message

Revision ID: ef151c063f97
Revises: 9841959e00f8
Create Date: 2019-12-30 15:28:09.486152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef151c063f97'
down_revision = '9841959e00f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('cancelled', sa.Boolean(),server_default='0', nullable=True))
    op.add_column('project', sa.Column('analyst_requested', sa.Boolean(),
                                       server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cancelled')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'analyst_requested')
    # ### end Alembic commands ###
