"""empty message

Revision ID: f2d9d8f0644f
Revises: cb1f50b28c5c
Create Date: 2018-04-05 22:24:24.629081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d9d8f0644f'
down_revision = 'cb1f50b28c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_access_event', sa.Column('dial_in_detail', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_access_event', 'dial_in_detail')
    # ### end Alembic commands ###
