"""empty message

Revision ID: f2e88caf785b
Revises: 9b8c5cda3a74
Create Date: 2020-01-02 15:28:34.323022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2e88caf785b'
down_revision = 'ef151c063f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('project_archive_file', sa.Column('visible_to_client', sa.Boolean(),server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_archive_file', 'visible_to_client')

    # ### end Alembic commands ###
