"""empty message

Revision ID: f90e11faba65
Revises: a8133d42df2c
Create Date: 2018-07-20 16:33:26.648458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90e11faba65'
down_revision = 'a8133d42df2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_request', sa.Column('accepted_terms', sa.Boolean(), nullable=True))
    op.execute("UPDATE registration_request SET accepted_terms=true")
    op.add_column('user', sa.Column('accepted_terms', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET accepted_terms=true')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'accepted_terms')
    op.drop_column('registration_request', 'accepted_terms')
    # ### end Alembic commands ###
