"""empty message

Revision ID: fb3e7c0e5450
Revises: f3989768ac30
Create Date: 2021-08-11 16:23:48.456127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb3e7c0e5450'
down_revision = 'e89b189441d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalised_video_master', sa.Column('video_poster_filename', sa.String(length=256), nullable=True))
    op.add_column('personalised_video_invitee', sa.Column('account_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalised_video_master', 'video_poster_filename')
    op.drop_column('personalised_video_invitee', 'account_id')
    # ### end Alembic commands ###
