Delete a webcast setting
---
tags:
  - Webcast Settings
parameters:
  - in: header
    name: Authorization
    required: true
    type: string
  - in: path
    name: row_id
    schema:
      type: int
    required: true
    description: 'The webcast setting to delete'
responses:
  204:
    description: 'webcast setting deleted'
  404:
    description: 'webcast setting id: <row_id> does not exist'
  500:
    description: 'Some unknown exception!'
