For creating new webcast Setting
---
tags:
  - Webcast Settings
parameters:
  - in: header
    name: Authorization
    type: string
  - in: body
    name: body
    schema:
      $ref: '#/definitions/WebcastSetting'
responses:
  201:
    description: 'webcast setting has been created'
    schema:
      content:
        application/json:
      schema:
        type: object
        required:
          - message
          - row_id
        properties:
          name:
            type: string
            default: 'webcast setting been created'
          row_id:
            type: int32
            description: 'row id of the generated webcast setting'
            default: 1
  400:
    description: 'No data sent'
  422:
    description: 'Error in data'
  500:
    description: 'Some unknown exception!'
definitions:
  WebcastSetting:
    properties:
      completion_message:
        maxLength: 512
        type: string
        x-nullable: true
      created_by:
        format: int32
        readOnly: true
        type: integer
      created_date:
        format: date-time
        readOnly: true
        type: string
        x-nullable: true
      creator:
        properties:
          account:
            properties:
              account_name:
                maxLength: 512
                minLength: 1
                type: string
              account_type:
                enum:
                - corporate
                - buy-side
                - sell-side
                - general investor
                - admin
                - guest
                type: string
              row_id:
                format: int32
                readOnly: true
                type: integer
            readOnly: true
            required:
            - account_name
            - account_type
            type: object
          profile:
            properties:
              designation:
                maxLength: 128
                type: string
                x-nullable: true
              designation_link:
                properties:
                  name:
                    maxLength: 256
                    minLength: 1
                    type: string
                  row_id:
                    format: int32
                    readOnly: true
                    type: integer
                readOnly: true
                required:
                - name
                type: object
              first_name:
                maxLength: 512
                minLength: 1
                type: string
              last_name:
                maxLength: 512
                minLength: 1
                type: string
              links:
                readOnly: true
                type: string
              profile_photo_url:
                format: url
                readOnly: true
                type: string
              profile_thumbnail_url:
                format: url
                readOnly: true
                type: string
            required:
            - first_name
            - last_name
            type: object
          row_id:
            format: int32
            readOnly: true
            type: integer
        readOnly: true
        required:
        - profile
        type: object
      links:
        readOnly: true
        type: string
      missed_message:
        maxLength: 512
        type: string
        x-nullable: true
      modified_date:
        format: date-time
        readOnly: true
        type: string
        x-nullable: true
      reminder_1:
        format: date-time
        type: string
        x-nullable: true
      reminder_2:
        format: date-time
        type: string
        x-nullable: true
      row_id:
        format: int32
        readOnly: true
        type: integer
      updated_by:
        format: int32
        readOnly: true
        type: integer
      webcast:
        properties:
          ended_at:
            format: date-time
            type: string
            x-nullable: true
          invite_banner_filename:
            maxLength: 256
            type: string
            x-nullable: true
          invite_logo_filename:
            maxLength: 256
            type: string
            x-nullable: true
          row_id:
            format: int32
            readOnly: true
            type: integer
          started_at:
            format: date-time
            type: string
            x-nullable: true
          title:
            maxLength: 256
            minLength: 1
            type: string
        readOnly: true
        required:
        - title
        type: object
      webcast_id:
        format: int32
        type: integer
      welcome_message:
        maxLength: 512
        type: string
        x-nullable: true
    required:
    - created_by
    - updated_by
    - webcast_id
    type: object
